// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/network/message/player/PlayerCommands.proto

package network.message.player;

public final class PlayerCommands {
  private PlayerCommands() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BaseCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BaseCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .AddSquadron addSquadron = 1;</code>
     */
    network.message.player.PlayerCommands.AddSquadron getAddSquadron();
    /**
     * <code>optional .AddSquadron addSquadron = 1;</code>
     */
    network.message.player.PlayerCommands.AddSquadronOrBuilder getAddSquadronOrBuilder();

    /**
     * <code>optional .PlaceObstacle placeObstacle = 2;</code>
     */
    network.message.player.PlayerCommands.PlaceObstacle getPlaceObstacle();
    /**
     * <code>optional .PlaceObstacle placeObstacle = 2;</code>
     */
    network.message.player.PlayerCommands.PlaceObstacleOrBuilder getPlaceObstacleOrBuilder();

    public network.message.player.PlayerCommands.BaseCommand.CommandCase getCommandCase();
  }
  /**
   * Protobuf type {@code BaseCommand}
   */
  public  static final class BaseCommand extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BaseCommand)
      BaseCommandOrBuilder {
    // Use BaseCommand.newBuilder() to construct.
    private BaseCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BaseCommand() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BaseCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              network.message.player.PlayerCommands.AddSquadron.Builder subBuilder = null;
              if (commandCase_ == 1) {
                subBuilder = ((network.message.player.PlayerCommands.AddSquadron) command_).toBuilder();
              }
              command_ =
                  input.readMessage(network.message.player.PlayerCommands.AddSquadron.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((network.message.player.PlayerCommands.AddSquadron) command_);
                command_ = subBuilder.buildPartial();
              }
              commandCase_ = 1;
              break;
            }
            case 18: {
              network.message.player.PlayerCommands.PlaceObstacle.Builder subBuilder = null;
              if (commandCase_ == 2) {
                subBuilder = ((network.message.player.PlayerCommands.PlaceObstacle) command_).toBuilder();
              }
              command_ =
                  input.readMessage(network.message.player.PlayerCommands.PlaceObstacle.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((network.message.player.PlayerCommands.PlaceObstacle) command_);
                command_ = subBuilder.buildPartial();
              }
              commandCase_ = 2;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.message.player.PlayerCommands.internal_static_BaseCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.message.player.PlayerCommands.internal_static_BaseCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.message.player.PlayerCommands.BaseCommand.class, network.message.player.PlayerCommands.BaseCommand.Builder.class);
    }

    private int commandCase_ = 0;
    private java.lang.Object command_;
    public enum CommandCase
        implements com.google.protobuf.Internal.EnumLite {
      ADDSQUADRON(1),
      PLACEOBSTACLE(2),
      COMMAND_NOT_SET(0);
      private int value = 0;
      private CommandCase(int value) {
        this.value = value;
      }
      public static CommandCase valueOf(int value) {
        switch (value) {
          case 1: return ADDSQUADRON;
          case 2: return PLACEOBSTACLE;
          case 0: return COMMAND_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public CommandCase
    getCommandCase() {
      return CommandCase.valueOf(
          commandCase_);
    }

    public static final int ADDSQUADRON_FIELD_NUMBER = 1;
    /**
     * <code>optional .AddSquadron addSquadron = 1;</code>
     */
    public network.message.player.PlayerCommands.AddSquadron getAddSquadron() {
      if (commandCase_ == 1) {
         return (network.message.player.PlayerCommands.AddSquadron) command_;
      }
      return network.message.player.PlayerCommands.AddSquadron.getDefaultInstance();
    }
    /**
     * <code>optional .AddSquadron addSquadron = 1;</code>
     */
    public network.message.player.PlayerCommands.AddSquadronOrBuilder getAddSquadronOrBuilder() {
      if (commandCase_ == 1) {
         return (network.message.player.PlayerCommands.AddSquadron) command_;
      }
      return network.message.player.PlayerCommands.AddSquadron.getDefaultInstance();
    }

    public static final int PLACEOBSTACLE_FIELD_NUMBER = 2;
    /**
     * <code>optional .PlaceObstacle placeObstacle = 2;</code>
     */
    public network.message.player.PlayerCommands.PlaceObstacle getPlaceObstacle() {
      if (commandCase_ == 2) {
         return (network.message.player.PlayerCommands.PlaceObstacle) command_;
      }
      return network.message.player.PlayerCommands.PlaceObstacle.getDefaultInstance();
    }
    /**
     * <code>optional .PlaceObstacle placeObstacle = 2;</code>
     */
    public network.message.player.PlayerCommands.PlaceObstacleOrBuilder getPlaceObstacleOrBuilder() {
      if (commandCase_ == 2) {
         return (network.message.player.PlayerCommands.PlaceObstacle) command_;
      }
      return network.message.player.PlayerCommands.PlaceObstacle.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (commandCase_ == 1) {
        output.writeMessage(1, (network.message.player.PlayerCommands.AddSquadron) command_);
      }
      if (commandCase_ == 2) {
        output.writeMessage(2, (network.message.player.PlayerCommands.PlaceObstacle) command_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (commandCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (network.message.player.PlayerCommands.AddSquadron) command_);
      }
      if (commandCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (network.message.player.PlayerCommands.PlaceObstacle) command_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static network.message.player.PlayerCommands.BaseCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.player.PlayerCommands.BaseCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.player.PlayerCommands.BaseCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.player.PlayerCommands.BaseCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.player.PlayerCommands.BaseCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.player.PlayerCommands.BaseCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static network.message.player.PlayerCommands.BaseCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static network.message.player.PlayerCommands.BaseCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static network.message.player.PlayerCommands.BaseCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.player.PlayerCommands.BaseCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(network.message.player.PlayerCommands.BaseCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BaseCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BaseCommand)
        network.message.player.PlayerCommands.BaseCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return network.message.player.PlayerCommands.internal_static_BaseCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return network.message.player.PlayerCommands.internal_static_BaseCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                network.message.player.PlayerCommands.BaseCommand.class, network.message.player.PlayerCommands.BaseCommand.Builder.class);
      }

      // Construct using network.message.player.PlayerCommands.BaseCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        commandCase_ = 0;
        command_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return network.message.player.PlayerCommands.internal_static_BaseCommand_descriptor;
      }

      public network.message.player.PlayerCommands.BaseCommand getDefaultInstanceForType() {
        return network.message.player.PlayerCommands.BaseCommand.getDefaultInstance();
      }

      public network.message.player.PlayerCommands.BaseCommand build() {
        network.message.player.PlayerCommands.BaseCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public network.message.player.PlayerCommands.BaseCommand buildPartial() {
        network.message.player.PlayerCommands.BaseCommand result = new network.message.player.PlayerCommands.BaseCommand(this);
        if (commandCase_ == 1) {
          if (addSquadronBuilder_ == null) {
            result.command_ = command_;
          } else {
            result.command_ = addSquadronBuilder_.build();
          }
        }
        if (commandCase_ == 2) {
          if (placeObstacleBuilder_ == null) {
            result.command_ = command_;
          } else {
            result.command_ = placeObstacleBuilder_.build();
          }
        }
        result.commandCase_ = commandCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof network.message.player.PlayerCommands.BaseCommand) {
          return mergeFrom((network.message.player.PlayerCommands.BaseCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(network.message.player.PlayerCommands.BaseCommand other) {
        if (other == network.message.player.PlayerCommands.BaseCommand.getDefaultInstance()) return this;
        switch (other.getCommandCase()) {
          case ADDSQUADRON: {
            mergeAddSquadron(other.getAddSquadron());
            break;
          }
          case PLACEOBSTACLE: {
            mergePlaceObstacle(other.getPlaceObstacle());
            break;
          }
          case COMMAND_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        network.message.player.PlayerCommands.BaseCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (network.message.player.PlayerCommands.BaseCommand) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int commandCase_ = 0;
      private java.lang.Object command_;
      public CommandCase
          getCommandCase() {
        return CommandCase.valueOf(
            commandCase_);
      }

      public Builder clearCommand() {
        commandCase_ = 0;
        command_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilder<
          network.message.player.PlayerCommands.AddSquadron, network.message.player.PlayerCommands.AddSquadron.Builder, network.message.player.PlayerCommands.AddSquadronOrBuilder> addSquadronBuilder_;
      /**
       * <code>optional .AddSquadron addSquadron = 1;</code>
       */
      public network.message.player.PlayerCommands.AddSquadron getAddSquadron() {
        if (addSquadronBuilder_ == null) {
          if (commandCase_ == 1) {
            return (network.message.player.PlayerCommands.AddSquadron) command_;
          }
          return network.message.player.PlayerCommands.AddSquadron.getDefaultInstance();
        } else {
          if (commandCase_ == 1) {
            return addSquadronBuilder_.getMessage();
          }
          return network.message.player.PlayerCommands.AddSquadron.getDefaultInstance();
        }
      }
      /**
       * <code>optional .AddSquadron addSquadron = 1;</code>
       */
      public Builder setAddSquadron(network.message.player.PlayerCommands.AddSquadron value) {
        if (addSquadronBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          command_ = value;
          onChanged();
        } else {
          addSquadronBuilder_.setMessage(value);
        }
        commandCase_ = 1;
        return this;
      }
      /**
       * <code>optional .AddSquadron addSquadron = 1;</code>
       */
      public Builder setAddSquadron(
          network.message.player.PlayerCommands.AddSquadron.Builder builderForValue) {
        if (addSquadronBuilder_ == null) {
          command_ = builderForValue.build();
          onChanged();
        } else {
          addSquadronBuilder_.setMessage(builderForValue.build());
        }
        commandCase_ = 1;
        return this;
      }
      /**
       * <code>optional .AddSquadron addSquadron = 1;</code>
       */
      public Builder mergeAddSquadron(network.message.player.PlayerCommands.AddSquadron value) {
        if (addSquadronBuilder_ == null) {
          if (commandCase_ == 1 &&
              command_ != network.message.player.PlayerCommands.AddSquadron.getDefaultInstance()) {
            command_ = network.message.player.PlayerCommands.AddSquadron.newBuilder((network.message.player.PlayerCommands.AddSquadron) command_)
                .mergeFrom(value).buildPartial();
          } else {
            command_ = value;
          }
          onChanged();
        } else {
          if (commandCase_ == 1) {
            addSquadronBuilder_.mergeFrom(value);
          }
          addSquadronBuilder_.setMessage(value);
        }
        commandCase_ = 1;
        return this;
      }
      /**
       * <code>optional .AddSquadron addSquadron = 1;</code>
       */
      public Builder clearAddSquadron() {
        if (addSquadronBuilder_ == null) {
          if (commandCase_ == 1) {
            commandCase_ = 0;
            command_ = null;
            onChanged();
          }
        } else {
          if (commandCase_ == 1) {
            commandCase_ = 0;
            command_ = null;
          }
          addSquadronBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .AddSquadron addSquadron = 1;</code>
       */
      public network.message.player.PlayerCommands.AddSquadron.Builder getAddSquadronBuilder() {
        return getAddSquadronFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .AddSquadron addSquadron = 1;</code>
       */
      public network.message.player.PlayerCommands.AddSquadronOrBuilder getAddSquadronOrBuilder() {
        if ((commandCase_ == 1) && (addSquadronBuilder_ != null)) {
          return addSquadronBuilder_.getMessageOrBuilder();
        } else {
          if (commandCase_ == 1) {
            return (network.message.player.PlayerCommands.AddSquadron) command_;
          }
          return network.message.player.PlayerCommands.AddSquadron.getDefaultInstance();
        }
      }
      /**
       * <code>optional .AddSquadron addSquadron = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          network.message.player.PlayerCommands.AddSquadron, network.message.player.PlayerCommands.AddSquadron.Builder, network.message.player.PlayerCommands.AddSquadronOrBuilder> 
          getAddSquadronFieldBuilder() {
        if (addSquadronBuilder_ == null) {
          if (!(commandCase_ == 1)) {
            command_ = network.message.player.PlayerCommands.AddSquadron.getDefaultInstance();
          }
          addSquadronBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              network.message.player.PlayerCommands.AddSquadron, network.message.player.PlayerCommands.AddSquadron.Builder, network.message.player.PlayerCommands.AddSquadronOrBuilder>(
                  (network.message.player.PlayerCommands.AddSquadron) command_,
                  getParentForChildren(),
                  isClean());
          command_ = null;
        }
        commandCase_ = 1;
        onChanged();;
        return addSquadronBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          network.message.player.PlayerCommands.PlaceObstacle, network.message.player.PlayerCommands.PlaceObstacle.Builder, network.message.player.PlayerCommands.PlaceObstacleOrBuilder> placeObstacleBuilder_;
      /**
       * <code>optional .PlaceObstacle placeObstacle = 2;</code>
       */
      public network.message.player.PlayerCommands.PlaceObstacle getPlaceObstacle() {
        if (placeObstacleBuilder_ == null) {
          if (commandCase_ == 2) {
            return (network.message.player.PlayerCommands.PlaceObstacle) command_;
          }
          return network.message.player.PlayerCommands.PlaceObstacle.getDefaultInstance();
        } else {
          if (commandCase_ == 2) {
            return placeObstacleBuilder_.getMessage();
          }
          return network.message.player.PlayerCommands.PlaceObstacle.getDefaultInstance();
        }
      }
      /**
       * <code>optional .PlaceObstacle placeObstacle = 2;</code>
       */
      public Builder setPlaceObstacle(network.message.player.PlayerCommands.PlaceObstacle value) {
        if (placeObstacleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          command_ = value;
          onChanged();
        } else {
          placeObstacleBuilder_.setMessage(value);
        }
        commandCase_ = 2;
        return this;
      }
      /**
       * <code>optional .PlaceObstacle placeObstacle = 2;</code>
       */
      public Builder setPlaceObstacle(
          network.message.player.PlayerCommands.PlaceObstacle.Builder builderForValue) {
        if (placeObstacleBuilder_ == null) {
          command_ = builderForValue.build();
          onChanged();
        } else {
          placeObstacleBuilder_.setMessage(builderForValue.build());
        }
        commandCase_ = 2;
        return this;
      }
      /**
       * <code>optional .PlaceObstacle placeObstacle = 2;</code>
       */
      public Builder mergePlaceObstacle(network.message.player.PlayerCommands.PlaceObstacle value) {
        if (placeObstacleBuilder_ == null) {
          if (commandCase_ == 2 &&
              command_ != network.message.player.PlayerCommands.PlaceObstacle.getDefaultInstance()) {
            command_ = network.message.player.PlayerCommands.PlaceObstacle.newBuilder((network.message.player.PlayerCommands.PlaceObstacle) command_)
                .mergeFrom(value).buildPartial();
          } else {
            command_ = value;
          }
          onChanged();
        } else {
          if (commandCase_ == 2) {
            placeObstacleBuilder_.mergeFrom(value);
          }
          placeObstacleBuilder_.setMessage(value);
        }
        commandCase_ = 2;
        return this;
      }
      /**
       * <code>optional .PlaceObstacle placeObstacle = 2;</code>
       */
      public Builder clearPlaceObstacle() {
        if (placeObstacleBuilder_ == null) {
          if (commandCase_ == 2) {
            commandCase_ = 0;
            command_ = null;
            onChanged();
          }
        } else {
          if (commandCase_ == 2) {
            commandCase_ = 0;
            command_ = null;
          }
          placeObstacleBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .PlaceObstacle placeObstacle = 2;</code>
       */
      public network.message.player.PlayerCommands.PlaceObstacle.Builder getPlaceObstacleBuilder() {
        return getPlaceObstacleFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .PlaceObstacle placeObstacle = 2;</code>
       */
      public network.message.player.PlayerCommands.PlaceObstacleOrBuilder getPlaceObstacleOrBuilder() {
        if ((commandCase_ == 2) && (placeObstacleBuilder_ != null)) {
          return placeObstacleBuilder_.getMessageOrBuilder();
        } else {
          if (commandCase_ == 2) {
            return (network.message.player.PlayerCommands.PlaceObstacle) command_;
          }
          return network.message.player.PlayerCommands.PlaceObstacle.getDefaultInstance();
        }
      }
      /**
       * <code>optional .PlaceObstacle placeObstacle = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          network.message.player.PlayerCommands.PlaceObstacle, network.message.player.PlayerCommands.PlaceObstacle.Builder, network.message.player.PlayerCommands.PlaceObstacleOrBuilder> 
          getPlaceObstacleFieldBuilder() {
        if (placeObstacleBuilder_ == null) {
          if (!(commandCase_ == 2)) {
            command_ = network.message.player.PlayerCommands.PlaceObstacle.getDefaultInstance();
          }
          placeObstacleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              network.message.player.PlayerCommands.PlaceObstacle, network.message.player.PlayerCommands.PlaceObstacle.Builder, network.message.player.PlayerCommands.PlaceObstacleOrBuilder>(
                  (network.message.player.PlayerCommands.PlaceObstacle) command_,
                  getParentForChildren(),
                  isClean());
          command_ = null;
        }
        commandCase_ = 2;
        onChanged();;
        return placeObstacleBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:BaseCommand)
    }

    // @@protoc_insertion_point(class_scope:BaseCommand)
    private static final network.message.player.PlayerCommands.BaseCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new network.message.player.PlayerCommands.BaseCommand();
    }

    public static network.message.player.PlayerCommands.BaseCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseCommand>
        PARSER = new com.google.protobuf.AbstractParser<BaseCommand>() {
      public BaseCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new BaseCommand(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<BaseCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseCommand> getParserForType() {
      return PARSER;
    }

    public network.message.player.PlayerCommands.BaseCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddSquadronOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AddSquadron)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 faction = 1;</code>
     */
    int getFaction();

    /**
     * <code>repeated int32 selectedObstacleTypes = 2;</code>
     */
    java.util.List<java.lang.Integer> getSelectedObstacleTypesList();
    /**
     * <code>repeated int32 selectedObstacleTypes = 2;</code>
     */
    int getSelectedObstacleTypesCount();
    /**
     * <code>repeated int32 selectedObstacleTypes = 2;</code>
     */
    int getSelectedObstacleTypes(int index);

    /**
     * <code>repeated .UnitSubmission units = 3;</code>
     */
    java.util.List<network.message.player.PlayerCommands.UnitSubmission> 
        getUnitsList();
    /**
     * <code>repeated .UnitSubmission units = 3;</code>
     */
    network.message.player.PlayerCommands.UnitSubmission getUnits(int index);
    /**
     * <code>repeated .UnitSubmission units = 3;</code>
     */
    int getUnitsCount();
    /**
     * <code>repeated .UnitSubmission units = 3;</code>
     */
    java.util.List<? extends network.message.player.PlayerCommands.UnitSubmissionOrBuilder> 
        getUnitsOrBuilderList();
    /**
     * <code>repeated .UnitSubmission units = 3;</code>
     */
    network.message.player.PlayerCommands.UnitSubmissionOrBuilder getUnitsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code AddSquadron}
   */
  public  static final class AddSquadron extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:AddSquadron)
      AddSquadronOrBuilder {
    // Use AddSquadron.newBuilder() to construct.
    private AddSquadron(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AddSquadron() {
      faction_ = 0;
      selectedObstacleTypes_ = java.util.Collections.emptyList();
      units_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AddSquadron(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              faction_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                selectedObstacleTypes_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              selectedObstacleTypes_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                selectedObstacleTypes_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                selectedObstacleTypes_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                units_ = new java.util.ArrayList<network.message.player.PlayerCommands.UnitSubmission>();
                mutable_bitField0_ |= 0x00000004;
              }
              units_.add(input.readMessage(network.message.player.PlayerCommands.UnitSubmission.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          selectedObstacleTypes_ = java.util.Collections.unmodifiableList(selectedObstacleTypes_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          units_ = java.util.Collections.unmodifiableList(units_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.message.player.PlayerCommands.internal_static_AddSquadron_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.message.player.PlayerCommands.internal_static_AddSquadron_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.message.player.PlayerCommands.AddSquadron.class, network.message.player.PlayerCommands.AddSquadron.Builder.class);
    }

    private int bitField0_;
    public static final int FACTION_FIELD_NUMBER = 1;
    private int faction_;
    /**
     * <code>optional int32 faction = 1;</code>
     */
    public int getFaction() {
      return faction_;
    }

    public static final int SELECTEDOBSTACLETYPES_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> selectedObstacleTypes_;
    /**
     * <code>repeated int32 selectedObstacleTypes = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getSelectedObstacleTypesList() {
      return selectedObstacleTypes_;
    }
    /**
     * <code>repeated int32 selectedObstacleTypes = 2;</code>
     */
    public int getSelectedObstacleTypesCount() {
      return selectedObstacleTypes_.size();
    }
    /**
     * <code>repeated int32 selectedObstacleTypes = 2;</code>
     */
    public int getSelectedObstacleTypes(int index) {
      return selectedObstacleTypes_.get(index);
    }
    private int selectedObstacleTypesMemoizedSerializedSize = -1;

    public static final int UNITS_FIELD_NUMBER = 3;
    private java.util.List<network.message.player.PlayerCommands.UnitSubmission> units_;
    /**
     * <code>repeated .UnitSubmission units = 3;</code>
     */
    public java.util.List<network.message.player.PlayerCommands.UnitSubmission> getUnitsList() {
      return units_;
    }
    /**
     * <code>repeated .UnitSubmission units = 3;</code>
     */
    public java.util.List<? extends network.message.player.PlayerCommands.UnitSubmissionOrBuilder> 
        getUnitsOrBuilderList() {
      return units_;
    }
    /**
     * <code>repeated .UnitSubmission units = 3;</code>
     */
    public int getUnitsCount() {
      return units_.size();
    }
    /**
     * <code>repeated .UnitSubmission units = 3;</code>
     */
    public network.message.player.PlayerCommands.UnitSubmission getUnits(int index) {
      return units_.get(index);
    }
    /**
     * <code>repeated .UnitSubmission units = 3;</code>
     */
    public network.message.player.PlayerCommands.UnitSubmissionOrBuilder getUnitsOrBuilder(
        int index) {
      return units_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (faction_ != 0) {
        output.writeInt32(1, faction_);
      }
      if (getSelectedObstacleTypesList().size() > 0) {
        output.writeRawVarint32(18);
        output.writeRawVarint32(selectedObstacleTypesMemoizedSerializedSize);
      }
      for (int i = 0; i < selectedObstacleTypes_.size(); i++) {
        output.writeInt32NoTag(selectedObstacleTypes_.get(i));
      }
      for (int i = 0; i < units_.size(); i++) {
        output.writeMessage(3, units_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (faction_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, faction_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < selectedObstacleTypes_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(selectedObstacleTypes_.get(i));
        }
        size += dataSize;
        if (!getSelectedObstacleTypesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        selectedObstacleTypesMemoizedSerializedSize = dataSize;
      }
      for (int i = 0; i < units_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, units_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static network.message.player.PlayerCommands.AddSquadron parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.player.PlayerCommands.AddSquadron parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.player.PlayerCommands.AddSquadron parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.player.PlayerCommands.AddSquadron parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.player.PlayerCommands.AddSquadron parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.player.PlayerCommands.AddSquadron parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static network.message.player.PlayerCommands.AddSquadron parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static network.message.player.PlayerCommands.AddSquadron parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static network.message.player.PlayerCommands.AddSquadron parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.player.PlayerCommands.AddSquadron parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(network.message.player.PlayerCommands.AddSquadron prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddSquadron}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AddSquadron)
        network.message.player.PlayerCommands.AddSquadronOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return network.message.player.PlayerCommands.internal_static_AddSquadron_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return network.message.player.PlayerCommands.internal_static_AddSquadron_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                network.message.player.PlayerCommands.AddSquadron.class, network.message.player.PlayerCommands.AddSquadron.Builder.class);
      }

      // Construct using network.message.player.PlayerCommands.AddSquadron.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUnitsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        faction_ = 0;

        selectedObstacleTypes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        if (unitsBuilder_ == null) {
          units_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          unitsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return network.message.player.PlayerCommands.internal_static_AddSquadron_descriptor;
      }

      public network.message.player.PlayerCommands.AddSquadron getDefaultInstanceForType() {
        return network.message.player.PlayerCommands.AddSquadron.getDefaultInstance();
      }

      public network.message.player.PlayerCommands.AddSquadron build() {
        network.message.player.PlayerCommands.AddSquadron result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public network.message.player.PlayerCommands.AddSquadron buildPartial() {
        network.message.player.PlayerCommands.AddSquadron result = new network.message.player.PlayerCommands.AddSquadron(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.faction_ = faction_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          selectedObstacleTypes_ = java.util.Collections.unmodifiableList(selectedObstacleTypes_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.selectedObstacleTypes_ = selectedObstacleTypes_;
        if (unitsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            units_ = java.util.Collections.unmodifiableList(units_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.units_ = units_;
        } else {
          result.units_ = unitsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof network.message.player.PlayerCommands.AddSquadron) {
          return mergeFrom((network.message.player.PlayerCommands.AddSquadron)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(network.message.player.PlayerCommands.AddSquadron other) {
        if (other == network.message.player.PlayerCommands.AddSquadron.getDefaultInstance()) return this;
        if (other.getFaction() != 0) {
          setFaction(other.getFaction());
        }
        if (!other.selectedObstacleTypes_.isEmpty()) {
          if (selectedObstacleTypes_.isEmpty()) {
            selectedObstacleTypes_ = other.selectedObstacleTypes_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSelectedObstacleTypesIsMutable();
            selectedObstacleTypes_.addAll(other.selectedObstacleTypes_);
          }
          onChanged();
        }
        if (unitsBuilder_ == null) {
          if (!other.units_.isEmpty()) {
            if (units_.isEmpty()) {
              units_ = other.units_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureUnitsIsMutable();
              units_.addAll(other.units_);
            }
            onChanged();
          }
        } else {
          if (!other.units_.isEmpty()) {
            if (unitsBuilder_.isEmpty()) {
              unitsBuilder_.dispose();
              unitsBuilder_ = null;
              units_ = other.units_;
              bitField0_ = (bitField0_ & ~0x00000004);
              unitsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getUnitsFieldBuilder() : null;
            } else {
              unitsBuilder_.addAllMessages(other.units_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        network.message.player.PlayerCommands.AddSquadron parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (network.message.player.PlayerCommands.AddSquadron) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int faction_ ;
      /**
       * <code>optional int32 faction = 1;</code>
       */
      public int getFaction() {
        return faction_;
      }
      /**
       * <code>optional int32 faction = 1;</code>
       */
      public Builder setFaction(int value) {
        
        faction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 faction = 1;</code>
       */
      public Builder clearFaction() {
        
        faction_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> selectedObstacleTypes_ = java.util.Collections.emptyList();
      private void ensureSelectedObstacleTypesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          selectedObstacleTypes_ = new java.util.ArrayList<java.lang.Integer>(selectedObstacleTypes_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 selectedObstacleTypes = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getSelectedObstacleTypesList() {
        return java.util.Collections.unmodifiableList(selectedObstacleTypes_);
      }
      /**
       * <code>repeated int32 selectedObstacleTypes = 2;</code>
       */
      public int getSelectedObstacleTypesCount() {
        return selectedObstacleTypes_.size();
      }
      /**
       * <code>repeated int32 selectedObstacleTypes = 2;</code>
       */
      public int getSelectedObstacleTypes(int index) {
        return selectedObstacleTypes_.get(index);
      }
      /**
       * <code>repeated int32 selectedObstacleTypes = 2;</code>
       */
      public Builder setSelectedObstacleTypes(
          int index, int value) {
        ensureSelectedObstacleTypesIsMutable();
        selectedObstacleTypes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 selectedObstacleTypes = 2;</code>
       */
      public Builder addSelectedObstacleTypes(int value) {
        ensureSelectedObstacleTypesIsMutable();
        selectedObstacleTypes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 selectedObstacleTypes = 2;</code>
       */
      public Builder addAllSelectedObstacleTypes(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSelectedObstacleTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, selectedObstacleTypes_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 selectedObstacleTypes = 2;</code>
       */
      public Builder clearSelectedObstacleTypes() {
        selectedObstacleTypes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private java.util.List<network.message.player.PlayerCommands.UnitSubmission> units_ =
        java.util.Collections.emptyList();
      private void ensureUnitsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          units_ = new java.util.ArrayList<network.message.player.PlayerCommands.UnitSubmission>(units_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          network.message.player.PlayerCommands.UnitSubmission, network.message.player.PlayerCommands.UnitSubmission.Builder, network.message.player.PlayerCommands.UnitSubmissionOrBuilder> unitsBuilder_;

      /**
       * <code>repeated .UnitSubmission units = 3;</code>
       */
      public java.util.List<network.message.player.PlayerCommands.UnitSubmission> getUnitsList() {
        if (unitsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(units_);
        } else {
          return unitsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .UnitSubmission units = 3;</code>
       */
      public int getUnitsCount() {
        if (unitsBuilder_ == null) {
          return units_.size();
        } else {
          return unitsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .UnitSubmission units = 3;</code>
       */
      public network.message.player.PlayerCommands.UnitSubmission getUnits(int index) {
        if (unitsBuilder_ == null) {
          return units_.get(index);
        } else {
          return unitsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .UnitSubmission units = 3;</code>
       */
      public Builder setUnits(
          int index, network.message.player.PlayerCommands.UnitSubmission value) {
        if (unitsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUnitsIsMutable();
          units_.set(index, value);
          onChanged();
        } else {
          unitsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .UnitSubmission units = 3;</code>
       */
      public Builder setUnits(
          int index, network.message.player.PlayerCommands.UnitSubmission.Builder builderForValue) {
        if (unitsBuilder_ == null) {
          ensureUnitsIsMutable();
          units_.set(index, builderForValue.build());
          onChanged();
        } else {
          unitsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UnitSubmission units = 3;</code>
       */
      public Builder addUnits(network.message.player.PlayerCommands.UnitSubmission value) {
        if (unitsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUnitsIsMutable();
          units_.add(value);
          onChanged();
        } else {
          unitsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .UnitSubmission units = 3;</code>
       */
      public Builder addUnits(
          int index, network.message.player.PlayerCommands.UnitSubmission value) {
        if (unitsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUnitsIsMutable();
          units_.add(index, value);
          onChanged();
        } else {
          unitsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .UnitSubmission units = 3;</code>
       */
      public Builder addUnits(
          network.message.player.PlayerCommands.UnitSubmission.Builder builderForValue) {
        if (unitsBuilder_ == null) {
          ensureUnitsIsMutable();
          units_.add(builderForValue.build());
          onChanged();
        } else {
          unitsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UnitSubmission units = 3;</code>
       */
      public Builder addUnits(
          int index, network.message.player.PlayerCommands.UnitSubmission.Builder builderForValue) {
        if (unitsBuilder_ == null) {
          ensureUnitsIsMutable();
          units_.add(index, builderForValue.build());
          onChanged();
        } else {
          unitsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UnitSubmission units = 3;</code>
       */
      public Builder addAllUnits(
          java.lang.Iterable<? extends network.message.player.PlayerCommands.UnitSubmission> values) {
        if (unitsBuilder_ == null) {
          ensureUnitsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, units_);
          onChanged();
        } else {
          unitsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .UnitSubmission units = 3;</code>
       */
      public Builder clearUnits() {
        if (unitsBuilder_ == null) {
          units_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          unitsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .UnitSubmission units = 3;</code>
       */
      public Builder removeUnits(int index) {
        if (unitsBuilder_ == null) {
          ensureUnitsIsMutable();
          units_.remove(index);
          onChanged();
        } else {
          unitsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .UnitSubmission units = 3;</code>
       */
      public network.message.player.PlayerCommands.UnitSubmission.Builder getUnitsBuilder(
          int index) {
        return getUnitsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .UnitSubmission units = 3;</code>
       */
      public network.message.player.PlayerCommands.UnitSubmissionOrBuilder getUnitsOrBuilder(
          int index) {
        if (unitsBuilder_ == null) {
          return units_.get(index);  } else {
          return unitsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .UnitSubmission units = 3;</code>
       */
      public java.util.List<? extends network.message.player.PlayerCommands.UnitSubmissionOrBuilder> 
           getUnitsOrBuilderList() {
        if (unitsBuilder_ != null) {
          return unitsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(units_);
        }
      }
      /**
       * <code>repeated .UnitSubmission units = 3;</code>
       */
      public network.message.player.PlayerCommands.UnitSubmission.Builder addUnitsBuilder() {
        return getUnitsFieldBuilder().addBuilder(
            network.message.player.PlayerCommands.UnitSubmission.getDefaultInstance());
      }
      /**
       * <code>repeated .UnitSubmission units = 3;</code>
       */
      public network.message.player.PlayerCommands.UnitSubmission.Builder addUnitsBuilder(
          int index) {
        return getUnitsFieldBuilder().addBuilder(
            index, network.message.player.PlayerCommands.UnitSubmission.getDefaultInstance());
      }
      /**
       * <code>repeated .UnitSubmission units = 3;</code>
       */
      public java.util.List<network.message.player.PlayerCommands.UnitSubmission.Builder> 
           getUnitsBuilderList() {
        return getUnitsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          network.message.player.PlayerCommands.UnitSubmission, network.message.player.PlayerCommands.UnitSubmission.Builder, network.message.player.PlayerCommands.UnitSubmissionOrBuilder> 
          getUnitsFieldBuilder() {
        if (unitsBuilder_ == null) {
          unitsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              network.message.player.PlayerCommands.UnitSubmission, network.message.player.PlayerCommands.UnitSubmission.Builder, network.message.player.PlayerCommands.UnitSubmissionOrBuilder>(
                  units_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          units_ = null;
        }
        return unitsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:AddSquadron)
    }

    // @@protoc_insertion_point(class_scope:AddSquadron)
    private static final network.message.player.PlayerCommands.AddSquadron DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new network.message.player.PlayerCommands.AddSquadron();
    }

    public static network.message.player.PlayerCommands.AddSquadron getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddSquadron>
        PARSER = new com.google.protobuf.AbstractParser<AddSquadron>() {
      public AddSquadron parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new AddSquadron(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<AddSquadron> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddSquadron> getParserForType() {
      return PARSER;
    }

    public network.message.player.PlayerCommands.AddSquadron getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlaceObstacleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlaceObstacle)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 obstacleType = 1;</code>
     */
    int getObstacleType();

    /**
     * <code>repeated float transform = 2;</code>
     */
    java.util.List<java.lang.Float> getTransformList();
    /**
     * <code>repeated float transform = 2;</code>
     */
    int getTransformCount();
    /**
     * <code>repeated float transform = 2;</code>
     */
    float getTransform(int index);
  }
  /**
   * Protobuf type {@code PlaceObstacle}
   */
  public  static final class PlaceObstacle extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PlaceObstacle)
      PlaceObstacleOrBuilder {
    // Use PlaceObstacle.newBuilder() to construct.
    private PlaceObstacle(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PlaceObstacle() {
      obstacleType_ = 0;
      transform_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PlaceObstacle(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              obstacleType_ = input.readInt32();
              break;
            }
            case 21: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                transform_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000002;
              }
              transform_.add(input.readFloat());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                transform_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                transform_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          transform_ = java.util.Collections.unmodifiableList(transform_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.message.player.PlayerCommands.internal_static_PlaceObstacle_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.message.player.PlayerCommands.internal_static_PlaceObstacle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.message.player.PlayerCommands.PlaceObstacle.class, network.message.player.PlayerCommands.PlaceObstacle.Builder.class);
    }

    private int bitField0_;
    public static final int OBSTACLETYPE_FIELD_NUMBER = 1;
    private int obstacleType_;
    /**
     * <code>optional int32 obstacleType = 1;</code>
     */
    public int getObstacleType() {
      return obstacleType_;
    }

    public static final int TRANSFORM_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Float> transform_;
    /**
     * <code>repeated float transform = 2;</code>
     */
    public java.util.List<java.lang.Float>
        getTransformList() {
      return transform_;
    }
    /**
     * <code>repeated float transform = 2;</code>
     */
    public int getTransformCount() {
      return transform_.size();
    }
    /**
     * <code>repeated float transform = 2;</code>
     */
    public float getTransform(int index) {
      return transform_.get(index);
    }
    private int transformMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (obstacleType_ != 0) {
        output.writeInt32(1, obstacleType_);
      }
      if (getTransformList().size() > 0) {
        output.writeRawVarint32(18);
        output.writeRawVarint32(transformMemoizedSerializedSize);
      }
      for (int i = 0; i < transform_.size(); i++) {
        output.writeFloatNoTag(transform_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (obstacleType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, obstacleType_);
      }
      {
        int dataSize = 0;
        dataSize = 4 * getTransformList().size();
        size += dataSize;
        if (!getTransformList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        transformMemoizedSerializedSize = dataSize;
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static network.message.player.PlayerCommands.PlaceObstacle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.player.PlayerCommands.PlaceObstacle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.player.PlayerCommands.PlaceObstacle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.player.PlayerCommands.PlaceObstacle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.player.PlayerCommands.PlaceObstacle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.player.PlayerCommands.PlaceObstacle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static network.message.player.PlayerCommands.PlaceObstacle parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static network.message.player.PlayerCommands.PlaceObstacle parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static network.message.player.PlayerCommands.PlaceObstacle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.player.PlayerCommands.PlaceObstacle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(network.message.player.PlayerCommands.PlaceObstacle prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlaceObstacle}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlaceObstacle)
        network.message.player.PlayerCommands.PlaceObstacleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return network.message.player.PlayerCommands.internal_static_PlaceObstacle_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return network.message.player.PlayerCommands.internal_static_PlaceObstacle_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                network.message.player.PlayerCommands.PlaceObstacle.class, network.message.player.PlayerCommands.PlaceObstacle.Builder.class);
      }

      // Construct using network.message.player.PlayerCommands.PlaceObstacle.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        obstacleType_ = 0;

        transform_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return network.message.player.PlayerCommands.internal_static_PlaceObstacle_descriptor;
      }

      public network.message.player.PlayerCommands.PlaceObstacle getDefaultInstanceForType() {
        return network.message.player.PlayerCommands.PlaceObstacle.getDefaultInstance();
      }

      public network.message.player.PlayerCommands.PlaceObstacle build() {
        network.message.player.PlayerCommands.PlaceObstacle result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public network.message.player.PlayerCommands.PlaceObstacle buildPartial() {
        network.message.player.PlayerCommands.PlaceObstacle result = new network.message.player.PlayerCommands.PlaceObstacle(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.obstacleType_ = obstacleType_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          transform_ = java.util.Collections.unmodifiableList(transform_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.transform_ = transform_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof network.message.player.PlayerCommands.PlaceObstacle) {
          return mergeFrom((network.message.player.PlayerCommands.PlaceObstacle)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(network.message.player.PlayerCommands.PlaceObstacle other) {
        if (other == network.message.player.PlayerCommands.PlaceObstacle.getDefaultInstance()) return this;
        if (other.getObstacleType() != 0) {
          setObstacleType(other.getObstacleType());
        }
        if (!other.transform_.isEmpty()) {
          if (transform_.isEmpty()) {
            transform_ = other.transform_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTransformIsMutable();
            transform_.addAll(other.transform_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        network.message.player.PlayerCommands.PlaceObstacle parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (network.message.player.PlayerCommands.PlaceObstacle) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int obstacleType_ ;
      /**
       * <code>optional int32 obstacleType = 1;</code>
       */
      public int getObstacleType() {
        return obstacleType_;
      }
      /**
       * <code>optional int32 obstacleType = 1;</code>
       */
      public Builder setObstacleType(int value) {
        
        obstacleType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 obstacleType = 1;</code>
       */
      public Builder clearObstacleType() {
        
        obstacleType_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Float> transform_ = java.util.Collections.emptyList();
      private void ensureTransformIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          transform_ = new java.util.ArrayList<java.lang.Float>(transform_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated float transform = 2;</code>
       */
      public java.util.List<java.lang.Float>
          getTransformList() {
        return java.util.Collections.unmodifiableList(transform_);
      }
      /**
       * <code>repeated float transform = 2;</code>
       */
      public int getTransformCount() {
        return transform_.size();
      }
      /**
       * <code>repeated float transform = 2;</code>
       */
      public float getTransform(int index) {
        return transform_.get(index);
      }
      /**
       * <code>repeated float transform = 2;</code>
       */
      public Builder setTransform(
          int index, float value) {
        ensureTransformIsMutable();
        transform_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float transform = 2;</code>
       */
      public Builder addTransform(float value) {
        ensureTransformIsMutable();
        transform_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float transform = 2;</code>
       */
      public Builder addAllTransform(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureTransformIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, transform_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float transform = 2;</code>
       */
      public Builder clearTransform() {
        transform_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PlaceObstacle)
    }

    // @@protoc_insertion_point(class_scope:PlaceObstacle)
    private static final network.message.player.PlayerCommands.PlaceObstacle DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new network.message.player.PlayerCommands.PlaceObstacle();
    }

    public static network.message.player.PlayerCommands.PlaceObstacle getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlaceObstacle>
        PARSER = new com.google.protobuf.AbstractParser<PlaceObstacle>() {
      public PlaceObstacle parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new PlaceObstacle(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<PlaceObstacle> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlaceObstacle> getParserForType() {
      return PARSER;
    }

    public network.message.player.PlayerCommands.PlaceObstacle getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UnitSubmissionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UnitSubmission)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code UnitSubmission}
   *
   * <pre>
   * Ship
   * Pilot
   * Upgrade
   * </pre>
   */
  public  static final class UnitSubmission extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:UnitSubmission)
      UnitSubmissionOrBuilder {
    // Use UnitSubmission.newBuilder() to construct.
    private UnitSubmission(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UnitSubmission() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UnitSubmission(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.message.player.PlayerCommands.internal_static_UnitSubmission_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.message.player.PlayerCommands.internal_static_UnitSubmission_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.message.player.PlayerCommands.UnitSubmission.class, network.message.player.PlayerCommands.UnitSubmission.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static network.message.player.PlayerCommands.UnitSubmission parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.player.PlayerCommands.UnitSubmission parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.player.PlayerCommands.UnitSubmission parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.player.PlayerCommands.UnitSubmission parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.player.PlayerCommands.UnitSubmission parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.player.PlayerCommands.UnitSubmission parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static network.message.player.PlayerCommands.UnitSubmission parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static network.message.player.PlayerCommands.UnitSubmission parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static network.message.player.PlayerCommands.UnitSubmission parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.player.PlayerCommands.UnitSubmission parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(network.message.player.PlayerCommands.UnitSubmission prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UnitSubmission}
     *
     * <pre>
     * Ship
     * Pilot
     * Upgrade
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UnitSubmission)
        network.message.player.PlayerCommands.UnitSubmissionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return network.message.player.PlayerCommands.internal_static_UnitSubmission_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return network.message.player.PlayerCommands.internal_static_UnitSubmission_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                network.message.player.PlayerCommands.UnitSubmission.class, network.message.player.PlayerCommands.UnitSubmission.Builder.class);
      }

      // Construct using network.message.player.PlayerCommands.UnitSubmission.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return network.message.player.PlayerCommands.internal_static_UnitSubmission_descriptor;
      }

      public network.message.player.PlayerCommands.UnitSubmission getDefaultInstanceForType() {
        return network.message.player.PlayerCommands.UnitSubmission.getDefaultInstance();
      }

      public network.message.player.PlayerCommands.UnitSubmission build() {
        network.message.player.PlayerCommands.UnitSubmission result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public network.message.player.PlayerCommands.UnitSubmission buildPartial() {
        network.message.player.PlayerCommands.UnitSubmission result = new network.message.player.PlayerCommands.UnitSubmission(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof network.message.player.PlayerCommands.UnitSubmission) {
          return mergeFrom((network.message.player.PlayerCommands.UnitSubmission)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(network.message.player.PlayerCommands.UnitSubmission other) {
        if (other == network.message.player.PlayerCommands.UnitSubmission.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        network.message.player.PlayerCommands.UnitSubmission parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (network.message.player.PlayerCommands.UnitSubmission) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:UnitSubmission)
    }

    // @@protoc_insertion_point(class_scope:UnitSubmission)
    private static final network.message.player.PlayerCommands.UnitSubmission DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new network.message.player.PlayerCommands.UnitSubmission();
    }

    public static network.message.player.PlayerCommands.UnitSubmission getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UnitSubmission>
        PARSER = new com.google.protobuf.AbstractParser<UnitSubmission>() {
      public UnitSubmission parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new UnitSubmission(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<UnitSubmission> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UnitSubmission> getParserForType() {
      return PARSER;
    }

    public network.message.player.PlayerCommands.UnitSubmission getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BaseCommand_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AddSquadron_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddSquadron_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PlaceObstacle_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlaceObstacle_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_UnitSubmission_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UnitSubmission_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:src/main/proto/network/message/player/" +
      "PlayerCommands.proto\"f\n\013BaseCommand\022#\n\013a" +
      "ddSquadron\030\001 \001(\0132\014.AddSquadronH\000\022\'\n\rplac" +
      "eObstacle\030\002 \001(\0132\016.PlaceObstacleH\000B\t\n\007com" +
      "mand\"]\n\013AddSquadron\022\017\n\007faction\030\001 \001(\005\022\035\n\025" +
      "selectedObstacleTypes\030\002 \003(\005\022\036\n\005units\030\003 \003" +
      "(\0132\017.UnitSubmission\"8\n\rPlaceObstacle\022\024\n\014" +
      "obstacleType\030\001 \001(\005\022\021\n\ttransform\030\002 \003(\002\"\020\n" +
      "\016UnitSubmissionB(\n\026network.message.playe" +
      "rB\016PlayerCommandsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BaseCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BaseCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BaseCommand_descriptor,
        new java.lang.String[] { "AddSquadron", "PlaceObstacle", "Command", });
    internal_static_AddSquadron_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AddSquadron_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AddSquadron_descriptor,
        new java.lang.String[] { "Faction", "SelectedObstacleTypes", "Units", });
    internal_static_PlaceObstacle_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PlaceObstacle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PlaceObstacle_descriptor,
        new java.lang.String[] { "ObstacleType", "Transform", });
    internal_static_UnitSubmission_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UnitSubmission_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UnitSubmission_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
