// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/network/message/PlayerResponses.proto

package network.message;

public final class PlayerResponses {
  private PlayerResponses() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BaseResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:player.responses.BaseResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 messageId = 1;</code>
     */
    int getMessageId();

    /**
     * <code>optional .player.responses.Command command = 2;</code>
     */
    network.message.PlayerResponses.Command getCommand();
    /**
     * <code>optional .player.responses.Command command = 2;</code>
     */
    network.message.PlayerResponses.CommandOrBuilder getCommandOrBuilder();

    public network.message.PlayerResponses.BaseResponse.ResponseCase getResponseCase();
  }
  /**
   * Protobuf type {@code player.responses.BaseResponse}
   */
  public  static final class BaseResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:player.responses.BaseResponse)
      BaseResponseOrBuilder {
    // Use BaseResponse.newBuilder() to construct.
    private BaseResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BaseResponse() {
      messageId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BaseResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              messageId_ = input.readInt32();
              break;
            }
            case 18: {
              network.message.PlayerResponses.Command.Builder subBuilder = null;
              if (responseCase_ == 2) {
                subBuilder = ((network.message.PlayerResponses.Command) response_).toBuilder();
              }
              response_ =
                  input.readMessage(network.message.PlayerResponses.Command.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((network.message.PlayerResponses.Command) response_);
                response_ = subBuilder.buildPartial();
              }
              responseCase_ = 2;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.message.PlayerResponses.internal_static_player_responses_BaseResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.message.PlayerResponses.internal_static_player_responses_BaseResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.message.PlayerResponses.BaseResponse.class, network.message.PlayerResponses.BaseResponse.Builder.class);
    }

    private int responseCase_ = 0;
    private java.lang.Object response_;
    public enum ResponseCase
        implements com.google.protobuf.Internal.EnumLite {
      COMMAND(2),
      RESPONSE_NOT_SET(0);
      private int value = 0;
      private ResponseCase(int value) {
        this.value = value;
      }
      public static ResponseCase valueOf(int value) {
        switch (value) {
          case 2: return COMMAND;
          case 0: return RESPONSE_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ResponseCase
    getResponseCase() {
      return ResponseCase.valueOf(
          responseCase_);
    }

    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private int messageId_;
    /**
     * <code>optional int32 messageId = 1;</code>
     */
    public int getMessageId() {
      return messageId_;
    }

    public static final int COMMAND_FIELD_NUMBER = 2;
    /**
     * <code>optional .player.responses.Command command = 2;</code>
     */
    public network.message.PlayerResponses.Command getCommand() {
      if (responseCase_ == 2) {
         return (network.message.PlayerResponses.Command) response_;
      }
      return network.message.PlayerResponses.Command.getDefaultInstance();
    }
    /**
     * <code>optional .player.responses.Command command = 2;</code>
     */
    public network.message.PlayerResponses.CommandOrBuilder getCommandOrBuilder() {
      if (responseCase_ == 2) {
         return (network.message.PlayerResponses.Command) response_;
      }
      return network.message.PlayerResponses.Command.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageId_ != 0) {
        output.writeInt32(1, messageId_);
      }
      if (responseCase_ == 2) {
        output.writeMessage(2, (network.message.PlayerResponses.Command) response_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, messageId_);
      }
      if (responseCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (network.message.PlayerResponses.Command) response_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static network.message.PlayerResponses.BaseResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.PlayerResponses.BaseResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.PlayerResponses.BaseResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.PlayerResponses.BaseResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.PlayerResponses.BaseResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.PlayerResponses.BaseResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static network.message.PlayerResponses.BaseResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static network.message.PlayerResponses.BaseResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static network.message.PlayerResponses.BaseResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.PlayerResponses.BaseResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(network.message.PlayerResponses.BaseResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code player.responses.BaseResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:player.responses.BaseResponse)
        network.message.PlayerResponses.BaseResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return network.message.PlayerResponses.internal_static_player_responses_BaseResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return network.message.PlayerResponses.internal_static_player_responses_BaseResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                network.message.PlayerResponses.BaseResponse.class, network.message.PlayerResponses.BaseResponse.Builder.class);
      }

      // Construct using network.message.PlayerResponses.BaseResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        messageId_ = 0;

        responseCase_ = 0;
        response_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return network.message.PlayerResponses.internal_static_player_responses_BaseResponse_descriptor;
      }

      public network.message.PlayerResponses.BaseResponse getDefaultInstanceForType() {
        return network.message.PlayerResponses.BaseResponse.getDefaultInstance();
      }

      public network.message.PlayerResponses.BaseResponse build() {
        network.message.PlayerResponses.BaseResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public network.message.PlayerResponses.BaseResponse buildPartial() {
        network.message.PlayerResponses.BaseResponse result = new network.message.PlayerResponses.BaseResponse(this);
        result.messageId_ = messageId_;
        if (responseCase_ == 2) {
          if (commandBuilder_ == null) {
            result.response_ = response_;
          } else {
            result.response_ = commandBuilder_.build();
          }
        }
        result.responseCase_ = responseCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof network.message.PlayerResponses.BaseResponse) {
          return mergeFrom((network.message.PlayerResponses.BaseResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(network.message.PlayerResponses.BaseResponse other) {
        if (other == network.message.PlayerResponses.BaseResponse.getDefaultInstance()) return this;
        if (other.getMessageId() != 0) {
          setMessageId(other.getMessageId());
        }
        switch (other.getResponseCase()) {
          case COMMAND: {
            mergeCommand(other.getCommand());
            break;
          }
          case RESPONSE_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        network.message.PlayerResponses.BaseResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (network.message.PlayerResponses.BaseResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int responseCase_ = 0;
      private java.lang.Object response_;
      public ResponseCase
          getResponseCase() {
        return ResponseCase.valueOf(
            responseCase_);
      }

      public Builder clearResponse() {
        responseCase_ = 0;
        response_ = null;
        onChanged();
        return this;
      }


      private int messageId_ ;
      /**
       * <code>optional int32 messageId = 1;</code>
       */
      public int getMessageId() {
        return messageId_;
      }
      /**
       * <code>optional int32 messageId = 1;</code>
       */
      public Builder setMessageId(int value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 messageId = 1;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilder<
          network.message.PlayerResponses.Command, network.message.PlayerResponses.Command.Builder, network.message.PlayerResponses.CommandOrBuilder> commandBuilder_;
      /**
       * <code>optional .player.responses.Command command = 2;</code>
       */
      public network.message.PlayerResponses.Command getCommand() {
        if (commandBuilder_ == null) {
          if (responseCase_ == 2) {
            return (network.message.PlayerResponses.Command) response_;
          }
          return network.message.PlayerResponses.Command.getDefaultInstance();
        } else {
          if (responseCase_ == 2) {
            return commandBuilder_.getMessage();
          }
          return network.message.PlayerResponses.Command.getDefaultInstance();
        }
      }
      /**
       * <code>optional .player.responses.Command command = 2;</code>
       */
      public Builder setCommand(network.message.PlayerResponses.Command value) {
        if (commandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          commandBuilder_.setMessage(value);
        }
        responseCase_ = 2;
        return this;
      }
      /**
       * <code>optional .player.responses.Command command = 2;</code>
       */
      public Builder setCommand(
          network.message.PlayerResponses.Command.Builder builderForValue) {
        if (commandBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          commandBuilder_.setMessage(builderForValue.build());
        }
        responseCase_ = 2;
        return this;
      }
      /**
       * <code>optional .player.responses.Command command = 2;</code>
       */
      public Builder mergeCommand(network.message.PlayerResponses.Command value) {
        if (commandBuilder_ == null) {
          if (responseCase_ == 2 &&
              response_ != network.message.PlayerResponses.Command.getDefaultInstance()) {
            response_ = network.message.PlayerResponses.Command.newBuilder((network.message.PlayerResponses.Command) response_)
                .mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          if (responseCase_ == 2) {
            commandBuilder_.mergeFrom(value);
          }
          commandBuilder_.setMessage(value);
        }
        responseCase_ = 2;
        return this;
      }
      /**
       * <code>optional .player.responses.Command command = 2;</code>
       */
      public Builder clearCommand() {
        if (commandBuilder_ == null) {
          if (responseCase_ == 2) {
            responseCase_ = 0;
            response_ = null;
            onChanged();
          }
        } else {
          if (responseCase_ == 2) {
            responseCase_ = 0;
            response_ = null;
          }
          commandBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .player.responses.Command command = 2;</code>
       */
      public network.message.PlayerResponses.Command.Builder getCommandBuilder() {
        return getCommandFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .player.responses.Command command = 2;</code>
       */
      public network.message.PlayerResponses.CommandOrBuilder getCommandOrBuilder() {
        if ((responseCase_ == 2) && (commandBuilder_ != null)) {
          return commandBuilder_.getMessageOrBuilder();
        } else {
          if (responseCase_ == 2) {
            return (network.message.PlayerResponses.Command) response_;
          }
          return network.message.PlayerResponses.Command.getDefaultInstance();
        }
      }
      /**
       * <code>optional .player.responses.Command command = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          network.message.PlayerResponses.Command, network.message.PlayerResponses.Command.Builder, network.message.PlayerResponses.CommandOrBuilder> 
          getCommandFieldBuilder() {
        if (commandBuilder_ == null) {
          if (!(responseCase_ == 2)) {
            response_ = network.message.PlayerResponses.Command.getDefaultInstance();
          }
          commandBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              network.message.PlayerResponses.Command, network.message.PlayerResponses.Command.Builder, network.message.PlayerResponses.CommandOrBuilder>(
                  (network.message.PlayerResponses.Command) response_,
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        responseCase_ = 2;
        onChanged();;
        return commandBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:player.responses.BaseResponse)
    }

    // @@protoc_insertion_point(class_scope:player.responses.BaseResponse)
    private static final network.message.PlayerResponses.BaseResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new network.message.PlayerResponses.BaseResponse();
    }

    public static network.message.PlayerResponses.BaseResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseResponse>
        PARSER = new com.google.protobuf.AbstractParser<BaseResponse>() {
      public BaseResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new BaseResponse(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<BaseResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseResponse> getParserForType() {
      return PARSER;
    }

    public network.message.PlayerResponses.BaseResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:player.responses.Command)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool accepted = 1;</code>
     */
    boolean getAccepted();
  }
  /**
   * Protobuf type {@code player.responses.Command}
   */
  public  static final class Command extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:player.responses.Command)
      CommandOrBuilder {
    // Use Command.newBuilder() to construct.
    private Command(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Command() {
      accepted_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Command(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              accepted_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.message.PlayerResponses.internal_static_player_responses_Command_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.message.PlayerResponses.internal_static_player_responses_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.message.PlayerResponses.Command.class, network.message.PlayerResponses.Command.Builder.class);
    }

    public static final int ACCEPTED_FIELD_NUMBER = 1;
    private boolean accepted_;
    /**
     * <code>optional bool accepted = 1;</code>
     */
    public boolean getAccepted() {
      return accepted_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (accepted_ != false) {
        output.writeBool(1, accepted_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (accepted_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, accepted_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static network.message.PlayerResponses.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.PlayerResponses.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.PlayerResponses.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.PlayerResponses.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.PlayerResponses.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.PlayerResponses.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static network.message.PlayerResponses.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static network.message.PlayerResponses.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static network.message.PlayerResponses.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.PlayerResponses.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(network.message.PlayerResponses.Command prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code player.responses.Command}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:player.responses.Command)
        network.message.PlayerResponses.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return network.message.PlayerResponses.internal_static_player_responses_Command_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return network.message.PlayerResponses.internal_static_player_responses_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                network.message.PlayerResponses.Command.class, network.message.PlayerResponses.Command.Builder.class);
      }

      // Construct using network.message.PlayerResponses.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        accepted_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return network.message.PlayerResponses.internal_static_player_responses_Command_descriptor;
      }

      public network.message.PlayerResponses.Command getDefaultInstanceForType() {
        return network.message.PlayerResponses.Command.getDefaultInstance();
      }

      public network.message.PlayerResponses.Command build() {
        network.message.PlayerResponses.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public network.message.PlayerResponses.Command buildPartial() {
        network.message.PlayerResponses.Command result = new network.message.PlayerResponses.Command(this);
        result.accepted_ = accepted_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof network.message.PlayerResponses.Command) {
          return mergeFrom((network.message.PlayerResponses.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(network.message.PlayerResponses.Command other) {
        if (other == network.message.PlayerResponses.Command.getDefaultInstance()) return this;
        if (other.getAccepted() != false) {
          setAccepted(other.getAccepted());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        network.message.PlayerResponses.Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (network.message.PlayerResponses.Command) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean accepted_ ;
      /**
       * <code>optional bool accepted = 1;</code>
       */
      public boolean getAccepted() {
        return accepted_;
      }
      /**
       * <code>optional bool accepted = 1;</code>
       */
      public Builder setAccepted(boolean value) {
        
        accepted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool accepted = 1;</code>
       */
      public Builder clearAccepted() {
        
        accepted_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:player.responses.Command)
    }

    // @@protoc_insertion_point(class_scope:player.responses.Command)
    private static final network.message.PlayerResponses.Command DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new network.message.PlayerResponses.Command();
    }

    public static network.message.PlayerResponses.Command getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Command>
        PARSER = new com.google.protobuf.AbstractParser<Command>() {
      public Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Command(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Command> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Command> getParserForType() {
      return PARSER;
    }

    public network.message.PlayerResponses.Command getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_player_responses_BaseResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_player_responses_BaseResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_player_responses_Command_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_player_responses_Command_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4src/main/proto/network/message/PlayerR" +
      "esponses.proto\022\020player.responses\"[\n\014Base" +
      "Response\022\021\n\tmessageId\030\001 \001(\005\022,\n\007command\030\002" +
      " \001(\0132\031.player.responses.CommandH\000B\n\n\010res" +
      "ponse\"\033\n\007Command\022\020\n\010accepted\030\001 \001(\010B\"\n\017ne" +
      "twork.messageB\017PlayerResponsesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_player_responses_BaseResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_player_responses_BaseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_player_responses_BaseResponse_descriptor,
        new java.lang.String[] { "MessageId", "Command", "Response", });
    internal_static_player_responses_Command_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_player_responses_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_player_responses_Command_descriptor,
        new java.lang.String[] { "Accepted", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
