// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/network/message/Message.proto

package network.message;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .player.commands.BaseCommand playerCommand = 1;</code>
     */
    network.message.PlayerCommands.BaseCommand getPlayerCommand();
    /**
     * <code>optional .player.commands.BaseCommand playerCommand = 1;</code>
     */
    network.message.PlayerCommands.BaseCommandOrBuilder getPlayerCommandOrBuilder();

    /**
     * <code>optional .player.responses.BaseResponse playerResponse = 2;</code>
     */
    network.message.PlayerResponses.BaseResponse getPlayerResponse();
    /**
     * <code>optional .player.responses.BaseResponse playerResponse = 2;</code>
     */
    network.message.PlayerResponses.BaseResponseOrBuilder getPlayerResponseOrBuilder();

    /**
     * <code>optional .server.commands.BaseCommand serverCommand = 3;</code>
     */
    network.message.ServerCommands.BaseCommand getServerCommand();
    /**
     * <code>optional .server.commands.BaseCommand serverCommand = 3;</code>
     */
    network.message.ServerCommands.BaseCommandOrBuilder getServerCommandOrBuilder();

    /**
     * <code>optional .server.responses.BaseResponse serverResponse = 4;</code>
     */
    network.message.ServerResponses.BaseResponse getServerResponse();
    /**
     * <code>optional .server.responses.BaseResponse serverResponse = 4;</code>
     */
    network.message.ServerResponses.BaseResponseOrBuilder getServerResponseOrBuilder();

    public network.message.Protocol.Message.SubMessageCase getSubMessageCase();
  }
  /**
   * Protobuf type {@code Message}
   *
   * <pre>
   * Wrapper class for commands and responses to allow for dynamic message reading
   * </pre>
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Message() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              network.message.PlayerCommands.BaseCommand.Builder subBuilder = null;
              if (subMessageCase_ == 1) {
                subBuilder = ((network.message.PlayerCommands.BaseCommand) subMessage_).toBuilder();
              }
              subMessage_ =
                  input.readMessage(network.message.PlayerCommands.BaseCommand.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((network.message.PlayerCommands.BaseCommand) subMessage_);
                subMessage_ = subBuilder.buildPartial();
              }
              subMessageCase_ = 1;
              break;
            }
            case 18: {
              network.message.PlayerResponses.BaseResponse.Builder subBuilder = null;
              if (subMessageCase_ == 2) {
                subBuilder = ((network.message.PlayerResponses.BaseResponse) subMessage_).toBuilder();
              }
              subMessage_ =
                  input.readMessage(network.message.PlayerResponses.BaseResponse.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((network.message.PlayerResponses.BaseResponse) subMessage_);
                subMessage_ = subBuilder.buildPartial();
              }
              subMessageCase_ = 2;
              break;
            }
            case 26: {
              network.message.ServerCommands.BaseCommand.Builder subBuilder = null;
              if (subMessageCase_ == 3) {
                subBuilder = ((network.message.ServerCommands.BaseCommand) subMessage_).toBuilder();
              }
              subMessage_ =
                  input.readMessage(network.message.ServerCommands.BaseCommand.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((network.message.ServerCommands.BaseCommand) subMessage_);
                subMessage_ = subBuilder.buildPartial();
              }
              subMessageCase_ = 3;
              break;
            }
            case 34: {
              network.message.ServerResponses.BaseResponse.Builder subBuilder = null;
              if (subMessageCase_ == 4) {
                subBuilder = ((network.message.ServerResponses.BaseResponse) subMessage_).toBuilder();
              }
              subMessage_ =
                  input.readMessage(network.message.ServerResponses.BaseResponse.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((network.message.ServerResponses.BaseResponse) subMessage_);
                subMessage_ = subBuilder.buildPartial();
              }
              subMessageCase_ = 4;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.message.Protocol.internal_static_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.message.Protocol.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.message.Protocol.Message.class, network.message.Protocol.Message.Builder.class);
    }

    private int subMessageCase_ = 0;
    private java.lang.Object subMessage_;
    public enum SubMessageCase
        implements com.google.protobuf.Internal.EnumLite {
      PLAYERCOMMAND(1),
      PLAYERRESPONSE(2),
      SERVERCOMMAND(3),
      SERVERRESPONSE(4),
      SUBMESSAGE_NOT_SET(0);
      private int value = 0;
      private SubMessageCase(int value) {
        this.value = value;
      }
      public static SubMessageCase valueOf(int value) {
        switch (value) {
          case 1: return PLAYERCOMMAND;
          case 2: return PLAYERRESPONSE;
          case 3: return SERVERCOMMAND;
          case 4: return SERVERRESPONSE;
          case 0: return SUBMESSAGE_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public SubMessageCase
    getSubMessageCase() {
      return SubMessageCase.valueOf(
          subMessageCase_);
    }

    public static final int PLAYERCOMMAND_FIELD_NUMBER = 1;
    /**
     * <code>optional .player.commands.BaseCommand playerCommand = 1;</code>
     */
    public network.message.PlayerCommands.BaseCommand getPlayerCommand() {
      if (subMessageCase_ == 1) {
         return (network.message.PlayerCommands.BaseCommand) subMessage_;
      }
      return network.message.PlayerCommands.BaseCommand.getDefaultInstance();
    }
    /**
     * <code>optional .player.commands.BaseCommand playerCommand = 1;</code>
     */
    public network.message.PlayerCommands.BaseCommandOrBuilder getPlayerCommandOrBuilder() {
      if (subMessageCase_ == 1) {
         return (network.message.PlayerCommands.BaseCommand) subMessage_;
      }
      return network.message.PlayerCommands.BaseCommand.getDefaultInstance();
    }

    public static final int PLAYERRESPONSE_FIELD_NUMBER = 2;
    /**
     * <code>optional .player.responses.BaseResponse playerResponse = 2;</code>
     */
    public network.message.PlayerResponses.BaseResponse getPlayerResponse() {
      if (subMessageCase_ == 2) {
         return (network.message.PlayerResponses.BaseResponse) subMessage_;
      }
      return network.message.PlayerResponses.BaseResponse.getDefaultInstance();
    }
    /**
     * <code>optional .player.responses.BaseResponse playerResponse = 2;</code>
     */
    public network.message.PlayerResponses.BaseResponseOrBuilder getPlayerResponseOrBuilder() {
      if (subMessageCase_ == 2) {
         return (network.message.PlayerResponses.BaseResponse) subMessage_;
      }
      return network.message.PlayerResponses.BaseResponse.getDefaultInstance();
    }

    public static final int SERVERCOMMAND_FIELD_NUMBER = 3;
    /**
     * <code>optional .server.commands.BaseCommand serverCommand = 3;</code>
     */
    public network.message.ServerCommands.BaseCommand getServerCommand() {
      if (subMessageCase_ == 3) {
         return (network.message.ServerCommands.BaseCommand) subMessage_;
      }
      return network.message.ServerCommands.BaseCommand.getDefaultInstance();
    }
    /**
     * <code>optional .server.commands.BaseCommand serverCommand = 3;</code>
     */
    public network.message.ServerCommands.BaseCommandOrBuilder getServerCommandOrBuilder() {
      if (subMessageCase_ == 3) {
         return (network.message.ServerCommands.BaseCommand) subMessage_;
      }
      return network.message.ServerCommands.BaseCommand.getDefaultInstance();
    }

    public static final int SERVERRESPONSE_FIELD_NUMBER = 4;
    /**
     * <code>optional .server.responses.BaseResponse serverResponse = 4;</code>
     */
    public network.message.ServerResponses.BaseResponse getServerResponse() {
      if (subMessageCase_ == 4) {
         return (network.message.ServerResponses.BaseResponse) subMessage_;
      }
      return network.message.ServerResponses.BaseResponse.getDefaultInstance();
    }
    /**
     * <code>optional .server.responses.BaseResponse serverResponse = 4;</code>
     */
    public network.message.ServerResponses.BaseResponseOrBuilder getServerResponseOrBuilder() {
      if (subMessageCase_ == 4) {
         return (network.message.ServerResponses.BaseResponse) subMessage_;
      }
      return network.message.ServerResponses.BaseResponse.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (subMessageCase_ == 1) {
        output.writeMessage(1, (network.message.PlayerCommands.BaseCommand) subMessage_);
      }
      if (subMessageCase_ == 2) {
        output.writeMessage(2, (network.message.PlayerResponses.BaseResponse) subMessage_);
      }
      if (subMessageCase_ == 3) {
        output.writeMessage(3, (network.message.ServerCommands.BaseCommand) subMessage_);
      }
      if (subMessageCase_ == 4) {
        output.writeMessage(4, (network.message.ServerResponses.BaseResponse) subMessage_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (subMessageCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (network.message.PlayerCommands.BaseCommand) subMessage_);
      }
      if (subMessageCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (network.message.PlayerResponses.BaseResponse) subMessage_);
      }
      if (subMessageCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (network.message.ServerCommands.BaseCommand) subMessage_);
      }
      if (subMessageCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (network.message.ServerResponses.BaseResponse) subMessage_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static network.message.Protocol.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.Protocol.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.Protocol.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.Protocol.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.Protocol.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.Protocol.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static network.message.Protocol.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static network.message.Protocol.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static network.message.Protocol.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.Protocol.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(network.message.Protocol.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     *
     * <pre>
     * Wrapper class for commands and responses to allow for dynamic message reading
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        network.message.Protocol.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return network.message.Protocol.internal_static_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return network.message.Protocol.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                network.message.Protocol.Message.class, network.message.Protocol.Message.Builder.class);
      }

      // Construct using network.message.Protocol.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        subMessageCase_ = 0;
        subMessage_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return network.message.Protocol.internal_static_Message_descriptor;
      }

      public network.message.Protocol.Message getDefaultInstanceForType() {
        return network.message.Protocol.Message.getDefaultInstance();
      }

      public network.message.Protocol.Message build() {
        network.message.Protocol.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public network.message.Protocol.Message buildPartial() {
        network.message.Protocol.Message result = new network.message.Protocol.Message(this);
        if (subMessageCase_ == 1) {
          if (playerCommandBuilder_ == null) {
            result.subMessage_ = subMessage_;
          } else {
            result.subMessage_ = playerCommandBuilder_.build();
          }
        }
        if (subMessageCase_ == 2) {
          if (playerResponseBuilder_ == null) {
            result.subMessage_ = subMessage_;
          } else {
            result.subMessage_ = playerResponseBuilder_.build();
          }
        }
        if (subMessageCase_ == 3) {
          if (serverCommandBuilder_ == null) {
            result.subMessage_ = subMessage_;
          } else {
            result.subMessage_ = serverCommandBuilder_.build();
          }
        }
        if (subMessageCase_ == 4) {
          if (serverResponseBuilder_ == null) {
            result.subMessage_ = subMessage_;
          } else {
            result.subMessage_ = serverResponseBuilder_.build();
          }
        }
        result.subMessageCase_ = subMessageCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof network.message.Protocol.Message) {
          return mergeFrom((network.message.Protocol.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(network.message.Protocol.Message other) {
        if (other == network.message.Protocol.Message.getDefaultInstance()) return this;
        switch (other.getSubMessageCase()) {
          case PLAYERCOMMAND: {
            mergePlayerCommand(other.getPlayerCommand());
            break;
          }
          case PLAYERRESPONSE: {
            mergePlayerResponse(other.getPlayerResponse());
            break;
          }
          case SERVERCOMMAND: {
            mergeServerCommand(other.getServerCommand());
            break;
          }
          case SERVERRESPONSE: {
            mergeServerResponse(other.getServerResponse());
            break;
          }
          case SUBMESSAGE_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        network.message.Protocol.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (network.message.Protocol.Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int subMessageCase_ = 0;
      private java.lang.Object subMessage_;
      public SubMessageCase
          getSubMessageCase() {
        return SubMessageCase.valueOf(
            subMessageCase_);
      }

      public Builder clearSubMessage() {
        subMessageCase_ = 0;
        subMessage_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilder<
          network.message.PlayerCommands.BaseCommand, network.message.PlayerCommands.BaseCommand.Builder, network.message.PlayerCommands.BaseCommandOrBuilder> playerCommandBuilder_;
      /**
       * <code>optional .player.commands.BaseCommand playerCommand = 1;</code>
       */
      public network.message.PlayerCommands.BaseCommand getPlayerCommand() {
        if (playerCommandBuilder_ == null) {
          if (subMessageCase_ == 1) {
            return (network.message.PlayerCommands.BaseCommand) subMessage_;
          }
          return network.message.PlayerCommands.BaseCommand.getDefaultInstance();
        } else {
          if (subMessageCase_ == 1) {
            return playerCommandBuilder_.getMessage();
          }
          return network.message.PlayerCommands.BaseCommand.getDefaultInstance();
        }
      }
      /**
       * <code>optional .player.commands.BaseCommand playerCommand = 1;</code>
       */
      public Builder setPlayerCommand(network.message.PlayerCommands.BaseCommand value) {
        if (playerCommandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          subMessage_ = value;
          onChanged();
        } else {
          playerCommandBuilder_.setMessage(value);
        }
        subMessageCase_ = 1;
        return this;
      }
      /**
       * <code>optional .player.commands.BaseCommand playerCommand = 1;</code>
       */
      public Builder setPlayerCommand(
          network.message.PlayerCommands.BaseCommand.Builder builderForValue) {
        if (playerCommandBuilder_ == null) {
          subMessage_ = builderForValue.build();
          onChanged();
        } else {
          playerCommandBuilder_.setMessage(builderForValue.build());
        }
        subMessageCase_ = 1;
        return this;
      }
      /**
       * <code>optional .player.commands.BaseCommand playerCommand = 1;</code>
       */
      public Builder mergePlayerCommand(network.message.PlayerCommands.BaseCommand value) {
        if (playerCommandBuilder_ == null) {
          if (subMessageCase_ == 1 &&
              subMessage_ != network.message.PlayerCommands.BaseCommand.getDefaultInstance()) {
            subMessage_ = network.message.PlayerCommands.BaseCommand.newBuilder((network.message.PlayerCommands.BaseCommand) subMessage_)
                .mergeFrom(value).buildPartial();
          } else {
            subMessage_ = value;
          }
          onChanged();
        } else {
          if (subMessageCase_ == 1) {
            playerCommandBuilder_.mergeFrom(value);
          }
          playerCommandBuilder_.setMessage(value);
        }
        subMessageCase_ = 1;
        return this;
      }
      /**
       * <code>optional .player.commands.BaseCommand playerCommand = 1;</code>
       */
      public Builder clearPlayerCommand() {
        if (playerCommandBuilder_ == null) {
          if (subMessageCase_ == 1) {
            subMessageCase_ = 0;
            subMessage_ = null;
            onChanged();
          }
        } else {
          if (subMessageCase_ == 1) {
            subMessageCase_ = 0;
            subMessage_ = null;
          }
          playerCommandBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .player.commands.BaseCommand playerCommand = 1;</code>
       */
      public network.message.PlayerCommands.BaseCommand.Builder getPlayerCommandBuilder() {
        return getPlayerCommandFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .player.commands.BaseCommand playerCommand = 1;</code>
       */
      public network.message.PlayerCommands.BaseCommandOrBuilder getPlayerCommandOrBuilder() {
        if ((subMessageCase_ == 1) && (playerCommandBuilder_ != null)) {
          return playerCommandBuilder_.getMessageOrBuilder();
        } else {
          if (subMessageCase_ == 1) {
            return (network.message.PlayerCommands.BaseCommand) subMessage_;
          }
          return network.message.PlayerCommands.BaseCommand.getDefaultInstance();
        }
      }
      /**
       * <code>optional .player.commands.BaseCommand playerCommand = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          network.message.PlayerCommands.BaseCommand, network.message.PlayerCommands.BaseCommand.Builder, network.message.PlayerCommands.BaseCommandOrBuilder> 
          getPlayerCommandFieldBuilder() {
        if (playerCommandBuilder_ == null) {
          if (!(subMessageCase_ == 1)) {
            subMessage_ = network.message.PlayerCommands.BaseCommand.getDefaultInstance();
          }
          playerCommandBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              network.message.PlayerCommands.BaseCommand, network.message.PlayerCommands.BaseCommand.Builder, network.message.PlayerCommands.BaseCommandOrBuilder>(
                  (network.message.PlayerCommands.BaseCommand) subMessage_,
                  getParentForChildren(),
                  isClean());
          subMessage_ = null;
        }
        subMessageCase_ = 1;
        onChanged();;
        return playerCommandBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          network.message.PlayerResponses.BaseResponse, network.message.PlayerResponses.BaseResponse.Builder, network.message.PlayerResponses.BaseResponseOrBuilder> playerResponseBuilder_;
      /**
       * <code>optional .player.responses.BaseResponse playerResponse = 2;</code>
       */
      public network.message.PlayerResponses.BaseResponse getPlayerResponse() {
        if (playerResponseBuilder_ == null) {
          if (subMessageCase_ == 2) {
            return (network.message.PlayerResponses.BaseResponse) subMessage_;
          }
          return network.message.PlayerResponses.BaseResponse.getDefaultInstance();
        } else {
          if (subMessageCase_ == 2) {
            return playerResponseBuilder_.getMessage();
          }
          return network.message.PlayerResponses.BaseResponse.getDefaultInstance();
        }
      }
      /**
       * <code>optional .player.responses.BaseResponse playerResponse = 2;</code>
       */
      public Builder setPlayerResponse(network.message.PlayerResponses.BaseResponse value) {
        if (playerResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          subMessage_ = value;
          onChanged();
        } else {
          playerResponseBuilder_.setMessage(value);
        }
        subMessageCase_ = 2;
        return this;
      }
      /**
       * <code>optional .player.responses.BaseResponse playerResponse = 2;</code>
       */
      public Builder setPlayerResponse(
          network.message.PlayerResponses.BaseResponse.Builder builderForValue) {
        if (playerResponseBuilder_ == null) {
          subMessage_ = builderForValue.build();
          onChanged();
        } else {
          playerResponseBuilder_.setMessage(builderForValue.build());
        }
        subMessageCase_ = 2;
        return this;
      }
      /**
       * <code>optional .player.responses.BaseResponse playerResponse = 2;</code>
       */
      public Builder mergePlayerResponse(network.message.PlayerResponses.BaseResponse value) {
        if (playerResponseBuilder_ == null) {
          if (subMessageCase_ == 2 &&
              subMessage_ != network.message.PlayerResponses.BaseResponse.getDefaultInstance()) {
            subMessage_ = network.message.PlayerResponses.BaseResponse.newBuilder((network.message.PlayerResponses.BaseResponse) subMessage_)
                .mergeFrom(value).buildPartial();
          } else {
            subMessage_ = value;
          }
          onChanged();
        } else {
          if (subMessageCase_ == 2) {
            playerResponseBuilder_.mergeFrom(value);
          }
          playerResponseBuilder_.setMessage(value);
        }
        subMessageCase_ = 2;
        return this;
      }
      /**
       * <code>optional .player.responses.BaseResponse playerResponse = 2;</code>
       */
      public Builder clearPlayerResponse() {
        if (playerResponseBuilder_ == null) {
          if (subMessageCase_ == 2) {
            subMessageCase_ = 0;
            subMessage_ = null;
            onChanged();
          }
        } else {
          if (subMessageCase_ == 2) {
            subMessageCase_ = 0;
            subMessage_ = null;
          }
          playerResponseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .player.responses.BaseResponse playerResponse = 2;</code>
       */
      public network.message.PlayerResponses.BaseResponse.Builder getPlayerResponseBuilder() {
        return getPlayerResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .player.responses.BaseResponse playerResponse = 2;</code>
       */
      public network.message.PlayerResponses.BaseResponseOrBuilder getPlayerResponseOrBuilder() {
        if ((subMessageCase_ == 2) && (playerResponseBuilder_ != null)) {
          return playerResponseBuilder_.getMessageOrBuilder();
        } else {
          if (subMessageCase_ == 2) {
            return (network.message.PlayerResponses.BaseResponse) subMessage_;
          }
          return network.message.PlayerResponses.BaseResponse.getDefaultInstance();
        }
      }
      /**
       * <code>optional .player.responses.BaseResponse playerResponse = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          network.message.PlayerResponses.BaseResponse, network.message.PlayerResponses.BaseResponse.Builder, network.message.PlayerResponses.BaseResponseOrBuilder> 
          getPlayerResponseFieldBuilder() {
        if (playerResponseBuilder_ == null) {
          if (!(subMessageCase_ == 2)) {
            subMessage_ = network.message.PlayerResponses.BaseResponse.getDefaultInstance();
          }
          playerResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              network.message.PlayerResponses.BaseResponse, network.message.PlayerResponses.BaseResponse.Builder, network.message.PlayerResponses.BaseResponseOrBuilder>(
                  (network.message.PlayerResponses.BaseResponse) subMessage_,
                  getParentForChildren(),
                  isClean());
          subMessage_ = null;
        }
        subMessageCase_ = 2;
        onChanged();;
        return playerResponseBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          network.message.ServerCommands.BaseCommand, network.message.ServerCommands.BaseCommand.Builder, network.message.ServerCommands.BaseCommandOrBuilder> serverCommandBuilder_;
      /**
       * <code>optional .server.commands.BaseCommand serverCommand = 3;</code>
       */
      public network.message.ServerCommands.BaseCommand getServerCommand() {
        if (serverCommandBuilder_ == null) {
          if (subMessageCase_ == 3) {
            return (network.message.ServerCommands.BaseCommand) subMessage_;
          }
          return network.message.ServerCommands.BaseCommand.getDefaultInstance();
        } else {
          if (subMessageCase_ == 3) {
            return serverCommandBuilder_.getMessage();
          }
          return network.message.ServerCommands.BaseCommand.getDefaultInstance();
        }
      }
      /**
       * <code>optional .server.commands.BaseCommand serverCommand = 3;</code>
       */
      public Builder setServerCommand(network.message.ServerCommands.BaseCommand value) {
        if (serverCommandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          subMessage_ = value;
          onChanged();
        } else {
          serverCommandBuilder_.setMessage(value);
        }
        subMessageCase_ = 3;
        return this;
      }
      /**
       * <code>optional .server.commands.BaseCommand serverCommand = 3;</code>
       */
      public Builder setServerCommand(
          network.message.ServerCommands.BaseCommand.Builder builderForValue) {
        if (serverCommandBuilder_ == null) {
          subMessage_ = builderForValue.build();
          onChanged();
        } else {
          serverCommandBuilder_.setMessage(builderForValue.build());
        }
        subMessageCase_ = 3;
        return this;
      }
      /**
       * <code>optional .server.commands.BaseCommand serverCommand = 3;</code>
       */
      public Builder mergeServerCommand(network.message.ServerCommands.BaseCommand value) {
        if (serverCommandBuilder_ == null) {
          if (subMessageCase_ == 3 &&
              subMessage_ != network.message.ServerCommands.BaseCommand.getDefaultInstance()) {
            subMessage_ = network.message.ServerCommands.BaseCommand.newBuilder((network.message.ServerCommands.BaseCommand) subMessage_)
                .mergeFrom(value).buildPartial();
          } else {
            subMessage_ = value;
          }
          onChanged();
        } else {
          if (subMessageCase_ == 3) {
            serverCommandBuilder_.mergeFrom(value);
          }
          serverCommandBuilder_.setMessage(value);
        }
        subMessageCase_ = 3;
        return this;
      }
      /**
       * <code>optional .server.commands.BaseCommand serverCommand = 3;</code>
       */
      public Builder clearServerCommand() {
        if (serverCommandBuilder_ == null) {
          if (subMessageCase_ == 3) {
            subMessageCase_ = 0;
            subMessage_ = null;
            onChanged();
          }
        } else {
          if (subMessageCase_ == 3) {
            subMessageCase_ = 0;
            subMessage_ = null;
          }
          serverCommandBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .server.commands.BaseCommand serverCommand = 3;</code>
       */
      public network.message.ServerCommands.BaseCommand.Builder getServerCommandBuilder() {
        return getServerCommandFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .server.commands.BaseCommand serverCommand = 3;</code>
       */
      public network.message.ServerCommands.BaseCommandOrBuilder getServerCommandOrBuilder() {
        if ((subMessageCase_ == 3) && (serverCommandBuilder_ != null)) {
          return serverCommandBuilder_.getMessageOrBuilder();
        } else {
          if (subMessageCase_ == 3) {
            return (network.message.ServerCommands.BaseCommand) subMessage_;
          }
          return network.message.ServerCommands.BaseCommand.getDefaultInstance();
        }
      }
      /**
       * <code>optional .server.commands.BaseCommand serverCommand = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          network.message.ServerCommands.BaseCommand, network.message.ServerCommands.BaseCommand.Builder, network.message.ServerCommands.BaseCommandOrBuilder> 
          getServerCommandFieldBuilder() {
        if (serverCommandBuilder_ == null) {
          if (!(subMessageCase_ == 3)) {
            subMessage_ = network.message.ServerCommands.BaseCommand.getDefaultInstance();
          }
          serverCommandBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              network.message.ServerCommands.BaseCommand, network.message.ServerCommands.BaseCommand.Builder, network.message.ServerCommands.BaseCommandOrBuilder>(
                  (network.message.ServerCommands.BaseCommand) subMessage_,
                  getParentForChildren(),
                  isClean());
          subMessage_ = null;
        }
        subMessageCase_ = 3;
        onChanged();;
        return serverCommandBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          network.message.ServerResponses.BaseResponse, network.message.ServerResponses.BaseResponse.Builder, network.message.ServerResponses.BaseResponseOrBuilder> serverResponseBuilder_;
      /**
       * <code>optional .server.responses.BaseResponse serverResponse = 4;</code>
       */
      public network.message.ServerResponses.BaseResponse getServerResponse() {
        if (serverResponseBuilder_ == null) {
          if (subMessageCase_ == 4) {
            return (network.message.ServerResponses.BaseResponse) subMessage_;
          }
          return network.message.ServerResponses.BaseResponse.getDefaultInstance();
        } else {
          if (subMessageCase_ == 4) {
            return serverResponseBuilder_.getMessage();
          }
          return network.message.ServerResponses.BaseResponse.getDefaultInstance();
        }
      }
      /**
       * <code>optional .server.responses.BaseResponse serverResponse = 4;</code>
       */
      public Builder setServerResponse(network.message.ServerResponses.BaseResponse value) {
        if (serverResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          subMessage_ = value;
          onChanged();
        } else {
          serverResponseBuilder_.setMessage(value);
        }
        subMessageCase_ = 4;
        return this;
      }
      /**
       * <code>optional .server.responses.BaseResponse serverResponse = 4;</code>
       */
      public Builder setServerResponse(
          network.message.ServerResponses.BaseResponse.Builder builderForValue) {
        if (serverResponseBuilder_ == null) {
          subMessage_ = builderForValue.build();
          onChanged();
        } else {
          serverResponseBuilder_.setMessage(builderForValue.build());
        }
        subMessageCase_ = 4;
        return this;
      }
      /**
       * <code>optional .server.responses.BaseResponse serverResponse = 4;</code>
       */
      public Builder mergeServerResponse(network.message.ServerResponses.BaseResponse value) {
        if (serverResponseBuilder_ == null) {
          if (subMessageCase_ == 4 &&
              subMessage_ != network.message.ServerResponses.BaseResponse.getDefaultInstance()) {
            subMessage_ = network.message.ServerResponses.BaseResponse.newBuilder((network.message.ServerResponses.BaseResponse) subMessage_)
                .mergeFrom(value).buildPartial();
          } else {
            subMessage_ = value;
          }
          onChanged();
        } else {
          if (subMessageCase_ == 4) {
            serverResponseBuilder_.mergeFrom(value);
          }
          serverResponseBuilder_.setMessage(value);
        }
        subMessageCase_ = 4;
        return this;
      }
      /**
       * <code>optional .server.responses.BaseResponse serverResponse = 4;</code>
       */
      public Builder clearServerResponse() {
        if (serverResponseBuilder_ == null) {
          if (subMessageCase_ == 4) {
            subMessageCase_ = 0;
            subMessage_ = null;
            onChanged();
          }
        } else {
          if (subMessageCase_ == 4) {
            subMessageCase_ = 0;
            subMessage_ = null;
          }
          serverResponseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .server.responses.BaseResponse serverResponse = 4;</code>
       */
      public network.message.ServerResponses.BaseResponse.Builder getServerResponseBuilder() {
        return getServerResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .server.responses.BaseResponse serverResponse = 4;</code>
       */
      public network.message.ServerResponses.BaseResponseOrBuilder getServerResponseOrBuilder() {
        if ((subMessageCase_ == 4) && (serverResponseBuilder_ != null)) {
          return serverResponseBuilder_.getMessageOrBuilder();
        } else {
          if (subMessageCase_ == 4) {
            return (network.message.ServerResponses.BaseResponse) subMessage_;
          }
          return network.message.ServerResponses.BaseResponse.getDefaultInstance();
        }
      }
      /**
       * <code>optional .server.responses.BaseResponse serverResponse = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          network.message.ServerResponses.BaseResponse, network.message.ServerResponses.BaseResponse.Builder, network.message.ServerResponses.BaseResponseOrBuilder> 
          getServerResponseFieldBuilder() {
        if (serverResponseBuilder_ == null) {
          if (!(subMessageCase_ == 4)) {
            subMessage_ = network.message.ServerResponses.BaseResponse.getDefaultInstance();
          }
          serverResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              network.message.ServerResponses.BaseResponse, network.message.ServerResponses.BaseResponse.Builder, network.message.ServerResponses.BaseResponseOrBuilder>(
                  (network.message.ServerResponses.BaseResponse) subMessage_,
                  getParentForChildren(),
                  isClean());
          subMessage_ = null;
        }
        subMessageCase_ = 4;
        onChanged();;
        return serverResponseBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final network.message.Protocol.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new network.message.Protocol.Message();
    }

    public static network.message.Protocol.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Message(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public network.message.Protocol.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,src/main/proto/network/message/Message" +
      ".proto\0323src/main/proto/network/message/P" +
      "layerCommands.proto\0324src/main/proto/netw" +
      "ork/message/PlayerResponses.proto\0323src/m" +
      "ain/proto/network/message/ServerCommands" +
      ".proto\0324src/main/proto/network/message/S" +
      "erverResponses.proto\"\371\001\n\007Message\0225\n\rplay" +
      "erCommand\030\001 \001(\0132\034.player.commands.BaseCo" +
      "mmandH\000\0228\n\016playerResponse\030\002 \001(\0132\036.player" +
      ".responses.BaseResponseH\000\0225\n\rserverComma",
      "nd\030\003 \001(\0132\034.server.commands.BaseCommandH\000" +
      "\0228\n\016serverResponse\030\004 \001(\0132\036.server.respon" +
      "ses.BaseResponseH\000B\014\n\nsubMessageB\033\n\017netw" +
      "ork.messageB\010Protocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          network.message.PlayerCommands.getDescriptor(),
          network.message.PlayerResponses.getDescriptor(),
          network.message.ServerCommands.getDescriptor(),
          network.message.ServerResponses.getDescriptor(),
        }, assigner);
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "PlayerCommand", "PlayerResponse", "ServerCommand", "ServerResponse", "SubMessage", });
    network.message.PlayerCommands.getDescriptor();
    network.message.PlayerResponses.getDescriptor();
    network.message.ServerCommands.getDescriptor();
    network.message.ServerResponses.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
