// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/network/message/ServerResponses.proto

package network.message;

public final class ServerResponses {
  private ServerResponses() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BaseResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:server.responses.BaseResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 clientId = 1;</code>
     */
    int getClientId();

    /**
     * <code>optional int32 messageId = 2;</code>
     */
    int getMessageId();

    /**
     * <code>optional .server.responses.Login login = 3;</code>
     */
    network.message.ServerResponses.Login getLogin();
    /**
     * <code>optional .server.responses.Login login = 3;</code>
     */
    network.message.ServerResponses.LoginOrBuilder getLoginOrBuilder();

    /**
     * <code>optional .server.responses.Command command = 4;</code>
     */
    network.message.ServerResponses.Command getCommand();
    /**
     * <code>optional .server.responses.Command command = 4;</code>
     */
    network.message.ServerResponses.CommandOrBuilder getCommandOrBuilder();

    public network.message.ServerResponses.BaseResponse.ResponseCase getResponseCase();
  }
  /**
   * Protobuf type {@code server.responses.BaseResponse}
   */
  public  static final class BaseResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:server.responses.BaseResponse)
      BaseResponseOrBuilder {
    // Use BaseResponse.newBuilder() to construct.
    private BaseResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BaseResponse() {
      clientId_ = 0;
      messageId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BaseResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              clientId_ = input.readInt32();
              break;
            }
            case 16: {

              messageId_ = input.readInt32();
              break;
            }
            case 26: {
              network.message.ServerResponses.Login.Builder subBuilder = null;
              if (responseCase_ == 3) {
                subBuilder = ((network.message.ServerResponses.Login) response_).toBuilder();
              }
              response_ =
                  input.readMessage(network.message.ServerResponses.Login.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((network.message.ServerResponses.Login) response_);
                response_ = subBuilder.buildPartial();
              }
              responseCase_ = 3;
              break;
            }
            case 34: {
              network.message.ServerResponses.Command.Builder subBuilder = null;
              if (responseCase_ == 4) {
                subBuilder = ((network.message.ServerResponses.Command) response_).toBuilder();
              }
              response_ =
                  input.readMessage(network.message.ServerResponses.Command.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((network.message.ServerResponses.Command) response_);
                response_ = subBuilder.buildPartial();
              }
              responseCase_ = 4;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.message.ServerResponses.internal_static_server_responses_BaseResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.message.ServerResponses.internal_static_server_responses_BaseResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.message.ServerResponses.BaseResponse.class, network.message.ServerResponses.BaseResponse.Builder.class);
    }

    private int responseCase_ = 0;
    private java.lang.Object response_;
    public enum ResponseCase
        implements com.google.protobuf.Internal.EnumLite {
      LOGIN(3),
      COMMAND(4),
      RESPONSE_NOT_SET(0);
      private int value = 0;
      private ResponseCase(int value) {
        this.value = value;
      }
      public static ResponseCase valueOf(int value) {
        switch (value) {
          case 3: return LOGIN;
          case 4: return COMMAND;
          case 0: return RESPONSE_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ResponseCase
    getResponseCase() {
      return ResponseCase.valueOf(
          responseCase_);
    }

    public static final int CLIENTID_FIELD_NUMBER = 1;
    private int clientId_;
    /**
     * <code>optional int32 clientId = 1;</code>
     */
    public int getClientId() {
      return clientId_;
    }

    public static final int MESSAGEID_FIELD_NUMBER = 2;
    private int messageId_;
    /**
     * <code>optional int32 messageId = 2;</code>
     */
    public int getMessageId() {
      return messageId_;
    }

    public static final int LOGIN_FIELD_NUMBER = 3;
    /**
     * <code>optional .server.responses.Login login = 3;</code>
     */
    public network.message.ServerResponses.Login getLogin() {
      if (responseCase_ == 3) {
         return (network.message.ServerResponses.Login) response_;
      }
      return network.message.ServerResponses.Login.getDefaultInstance();
    }
    /**
     * <code>optional .server.responses.Login login = 3;</code>
     */
    public network.message.ServerResponses.LoginOrBuilder getLoginOrBuilder() {
      if (responseCase_ == 3) {
         return (network.message.ServerResponses.Login) response_;
      }
      return network.message.ServerResponses.Login.getDefaultInstance();
    }

    public static final int COMMAND_FIELD_NUMBER = 4;
    /**
     * <code>optional .server.responses.Command command = 4;</code>
     */
    public network.message.ServerResponses.Command getCommand() {
      if (responseCase_ == 4) {
         return (network.message.ServerResponses.Command) response_;
      }
      return network.message.ServerResponses.Command.getDefaultInstance();
    }
    /**
     * <code>optional .server.responses.Command command = 4;</code>
     */
    public network.message.ServerResponses.CommandOrBuilder getCommandOrBuilder() {
      if (responseCase_ == 4) {
         return (network.message.ServerResponses.Command) response_;
      }
      return network.message.ServerResponses.Command.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (clientId_ != 0) {
        output.writeInt32(1, clientId_);
      }
      if (messageId_ != 0) {
        output.writeInt32(2, messageId_);
      }
      if (responseCase_ == 3) {
        output.writeMessage(3, (network.message.ServerResponses.Login) response_);
      }
      if (responseCase_ == 4) {
        output.writeMessage(4, (network.message.ServerResponses.Command) response_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (clientId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, clientId_);
      }
      if (messageId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, messageId_);
      }
      if (responseCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (network.message.ServerResponses.Login) response_);
      }
      if (responseCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (network.message.ServerResponses.Command) response_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static network.message.ServerResponses.BaseResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.ServerResponses.BaseResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.ServerResponses.BaseResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.ServerResponses.BaseResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.ServerResponses.BaseResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.ServerResponses.BaseResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static network.message.ServerResponses.BaseResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static network.message.ServerResponses.BaseResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static network.message.ServerResponses.BaseResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.ServerResponses.BaseResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(network.message.ServerResponses.BaseResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code server.responses.BaseResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:server.responses.BaseResponse)
        network.message.ServerResponses.BaseResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return network.message.ServerResponses.internal_static_server_responses_BaseResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return network.message.ServerResponses.internal_static_server_responses_BaseResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                network.message.ServerResponses.BaseResponse.class, network.message.ServerResponses.BaseResponse.Builder.class);
      }

      // Construct using network.message.ServerResponses.BaseResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        clientId_ = 0;

        messageId_ = 0;

        responseCase_ = 0;
        response_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return network.message.ServerResponses.internal_static_server_responses_BaseResponse_descriptor;
      }

      public network.message.ServerResponses.BaseResponse getDefaultInstanceForType() {
        return network.message.ServerResponses.BaseResponse.getDefaultInstance();
      }

      public network.message.ServerResponses.BaseResponse build() {
        network.message.ServerResponses.BaseResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public network.message.ServerResponses.BaseResponse buildPartial() {
        network.message.ServerResponses.BaseResponse result = new network.message.ServerResponses.BaseResponse(this);
        result.clientId_ = clientId_;
        result.messageId_ = messageId_;
        if (responseCase_ == 3) {
          if (loginBuilder_ == null) {
            result.response_ = response_;
          } else {
            result.response_ = loginBuilder_.build();
          }
        }
        if (responseCase_ == 4) {
          if (commandBuilder_ == null) {
            result.response_ = response_;
          } else {
            result.response_ = commandBuilder_.build();
          }
        }
        result.responseCase_ = responseCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof network.message.ServerResponses.BaseResponse) {
          return mergeFrom((network.message.ServerResponses.BaseResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(network.message.ServerResponses.BaseResponse other) {
        if (other == network.message.ServerResponses.BaseResponse.getDefaultInstance()) return this;
        if (other.getClientId() != 0) {
          setClientId(other.getClientId());
        }
        if (other.getMessageId() != 0) {
          setMessageId(other.getMessageId());
        }
        switch (other.getResponseCase()) {
          case LOGIN: {
            mergeLogin(other.getLogin());
            break;
          }
          case COMMAND: {
            mergeCommand(other.getCommand());
            break;
          }
          case RESPONSE_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        network.message.ServerResponses.BaseResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (network.message.ServerResponses.BaseResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int responseCase_ = 0;
      private java.lang.Object response_;
      public ResponseCase
          getResponseCase() {
        return ResponseCase.valueOf(
            responseCase_);
      }

      public Builder clearResponse() {
        responseCase_ = 0;
        response_ = null;
        onChanged();
        return this;
      }


      private int clientId_ ;
      /**
       * <code>optional int32 clientId = 1;</code>
       */
      public int getClientId() {
        return clientId_;
      }
      /**
       * <code>optional int32 clientId = 1;</code>
       */
      public Builder setClientId(int value) {
        
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 clientId = 1;</code>
       */
      public Builder clearClientId() {
        
        clientId_ = 0;
        onChanged();
        return this;
      }

      private int messageId_ ;
      /**
       * <code>optional int32 messageId = 2;</code>
       */
      public int getMessageId() {
        return messageId_;
      }
      /**
       * <code>optional int32 messageId = 2;</code>
       */
      public Builder setMessageId(int value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 messageId = 2;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilder<
          network.message.ServerResponses.Login, network.message.ServerResponses.Login.Builder, network.message.ServerResponses.LoginOrBuilder> loginBuilder_;
      /**
       * <code>optional .server.responses.Login login = 3;</code>
       */
      public network.message.ServerResponses.Login getLogin() {
        if (loginBuilder_ == null) {
          if (responseCase_ == 3) {
            return (network.message.ServerResponses.Login) response_;
          }
          return network.message.ServerResponses.Login.getDefaultInstance();
        } else {
          if (responseCase_ == 3) {
            return loginBuilder_.getMessage();
          }
          return network.message.ServerResponses.Login.getDefaultInstance();
        }
      }
      /**
       * <code>optional .server.responses.Login login = 3;</code>
       */
      public Builder setLogin(network.message.ServerResponses.Login value) {
        if (loginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          loginBuilder_.setMessage(value);
        }
        responseCase_ = 3;
        return this;
      }
      /**
       * <code>optional .server.responses.Login login = 3;</code>
       */
      public Builder setLogin(
          network.message.ServerResponses.Login.Builder builderForValue) {
        if (loginBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          loginBuilder_.setMessage(builderForValue.build());
        }
        responseCase_ = 3;
        return this;
      }
      /**
       * <code>optional .server.responses.Login login = 3;</code>
       */
      public Builder mergeLogin(network.message.ServerResponses.Login value) {
        if (loginBuilder_ == null) {
          if (responseCase_ == 3 &&
              response_ != network.message.ServerResponses.Login.getDefaultInstance()) {
            response_ = network.message.ServerResponses.Login.newBuilder((network.message.ServerResponses.Login) response_)
                .mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          if (responseCase_ == 3) {
            loginBuilder_.mergeFrom(value);
          }
          loginBuilder_.setMessage(value);
        }
        responseCase_ = 3;
        return this;
      }
      /**
       * <code>optional .server.responses.Login login = 3;</code>
       */
      public Builder clearLogin() {
        if (loginBuilder_ == null) {
          if (responseCase_ == 3) {
            responseCase_ = 0;
            response_ = null;
            onChanged();
          }
        } else {
          if (responseCase_ == 3) {
            responseCase_ = 0;
            response_ = null;
          }
          loginBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .server.responses.Login login = 3;</code>
       */
      public network.message.ServerResponses.Login.Builder getLoginBuilder() {
        return getLoginFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .server.responses.Login login = 3;</code>
       */
      public network.message.ServerResponses.LoginOrBuilder getLoginOrBuilder() {
        if ((responseCase_ == 3) && (loginBuilder_ != null)) {
          return loginBuilder_.getMessageOrBuilder();
        } else {
          if (responseCase_ == 3) {
            return (network.message.ServerResponses.Login) response_;
          }
          return network.message.ServerResponses.Login.getDefaultInstance();
        }
      }
      /**
       * <code>optional .server.responses.Login login = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          network.message.ServerResponses.Login, network.message.ServerResponses.Login.Builder, network.message.ServerResponses.LoginOrBuilder> 
          getLoginFieldBuilder() {
        if (loginBuilder_ == null) {
          if (!(responseCase_ == 3)) {
            response_ = network.message.ServerResponses.Login.getDefaultInstance();
          }
          loginBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              network.message.ServerResponses.Login, network.message.ServerResponses.Login.Builder, network.message.ServerResponses.LoginOrBuilder>(
                  (network.message.ServerResponses.Login) response_,
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        responseCase_ = 3;
        onChanged();;
        return loginBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          network.message.ServerResponses.Command, network.message.ServerResponses.Command.Builder, network.message.ServerResponses.CommandOrBuilder> commandBuilder_;
      /**
       * <code>optional .server.responses.Command command = 4;</code>
       */
      public network.message.ServerResponses.Command getCommand() {
        if (commandBuilder_ == null) {
          if (responseCase_ == 4) {
            return (network.message.ServerResponses.Command) response_;
          }
          return network.message.ServerResponses.Command.getDefaultInstance();
        } else {
          if (responseCase_ == 4) {
            return commandBuilder_.getMessage();
          }
          return network.message.ServerResponses.Command.getDefaultInstance();
        }
      }
      /**
       * <code>optional .server.responses.Command command = 4;</code>
       */
      public Builder setCommand(network.message.ServerResponses.Command value) {
        if (commandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          commandBuilder_.setMessage(value);
        }
        responseCase_ = 4;
        return this;
      }
      /**
       * <code>optional .server.responses.Command command = 4;</code>
       */
      public Builder setCommand(
          network.message.ServerResponses.Command.Builder builderForValue) {
        if (commandBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          commandBuilder_.setMessage(builderForValue.build());
        }
        responseCase_ = 4;
        return this;
      }
      /**
       * <code>optional .server.responses.Command command = 4;</code>
       */
      public Builder mergeCommand(network.message.ServerResponses.Command value) {
        if (commandBuilder_ == null) {
          if (responseCase_ == 4 &&
              response_ != network.message.ServerResponses.Command.getDefaultInstance()) {
            response_ = network.message.ServerResponses.Command.newBuilder((network.message.ServerResponses.Command) response_)
                .mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          if (responseCase_ == 4) {
            commandBuilder_.mergeFrom(value);
          }
          commandBuilder_.setMessage(value);
        }
        responseCase_ = 4;
        return this;
      }
      /**
       * <code>optional .server.responses.Command command = 4;</code>
       */
      public Builder clearCommand() {
        if (commandBuilder_ == null) {
          if (responseCase_ == 4) {
            responseCase_ = 0;
            response_ = null;
            onChanged();
          }
        } else {
          if (responseCase_ == 4) {
            responseCase_ = 0;
            response_ = null;
          }
          commandBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .server.responses.Command command = 4;</code>
       */
      public network.message.ServerResponses.Command.Builder getCommandBuilder() {
        return getCommandFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .server.responses.Command command = 4;</code>
       */
      public network.message.ServerResponses.CommandOrBuilder getCommandOrBuilder() {
        if ((responseCase_ == 4) && (commandBuilder_ != null)) {
          return commandBuilder_.getMessageOrBuilder();
        } else {
          if (responseCase_ == 4) {
            return (network.message.ServerResponses.Command) response_;
          }
          return network.message.ServerResponses.Command.getDefaultInstance();
        }
      }
      /**
       * <code>optional .server.responses.Command command = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          network.message.ServerResponses.Command, network.message.ServerResponses.Command.Builder, network.message.ServerResponses.CommandOrBuilder> 
          getCommandFieldBuilder() {
        if (commandBuilder_ == null) {
          if (!(responseCase_ == 4)) {
            response_ = network.message.ServerResponses.Command.getDefaultInstance();
          }
          commandBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              network.message.ServerResponses.Command, network.message.ServerResponses.Command.Builder, network.message.ServerResponses.CommandOrBuilder>(
                  (network.message.ServerResponses.Command) response_,
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        responseCase_ = 4;
        onChanged();;
        return commandBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:server.responses.BaseResponse)
    }

    // @@protoc_insertion_point(class_scope:server.responses.BaseResponse)
    private static final network.message.ServerResponses.BaseResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new network.message.ServerResponses.BaseResponse();
    }

    public static network.message.ServerResponses.BaseResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseResponse>
        PARSER = new com.google.protobuf.AbstractParser<BaseResponse>() {
      public BaseResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new BaseResponse(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<BaseResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseResponse> getParserForType() {
      return PARSER;
    }

    public network.message.ServerResponses.BaseResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:server.responses.Login)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 clientId = 1;</code>
     */
    int getClientId();

    /**
     * <code>optional int32 playerNum = 2;</code>
     */
    int getPlayerNum();
  }
  /**
   * Protobuf type {@code server.responses.Login}
   */
  public  static final class Login extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:server.responses.Login)
      LoginOrBuilder {
    // Use Login.newBuilder() to construct.
    private Login(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Login() {
      clientId_ = 0;
      playerNum_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Login(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              clientId_ = input.readInt32();
              break;
            }
            case 16: {

              playerNum_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.message.ServerResponses.internal_static_server_responses_Login_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.message.ServerResponses.internal_static_server_responses_Login_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.message.ServerResponses.Login.class, network.message.ServerResponses.Login.Builder.class);
    }

    public static final int CLIENTID_FIELD_NUMBER = 1;
    private int clientId_;
    /**
     * <code>optional int32 clientId = 1;</code>
     */
    public int getClientId() {
      return clientId_;
    }

    public static final int PLAYERNUM_FIELD_NUMBER = 2;
    private int playerNum_;
    /**
     * <code>optional int32 playerNum = 2;</code>
     */
    public int getPlayerNum() {
      return playerNum_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (clientId_ != 0) {
        output.writeInt32(1, clientId_);
      }
      if (playerNum_ != 0) {
        output.writeInt32(2, playerNum_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (clientId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, clientId_);
      }
      if (playerNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, playerNum_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static network.message.ServerResponses.Login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.ServerResponses.Login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.ServerResponses.Login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.ServerResponses.Login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.ServerResponses.Login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.ServerResponses.Login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static network.message.ServerResponses.Login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static network.message.ServerResponses.Login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static network.message.ServerResponses.Login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.ServerResponses.Login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(network.message.ServerResponses.Login prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code server.responses.Login}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:server.responses.Login)
        network.message.ServerResponses.LoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return network.message.ServerResponses.internal_static_server_responses_Login_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return network.message.ServerResponses.internal_static_server_responses_Login_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                network.message.ServerResponses.Login.class, network.message.ServerResponses.Login.Builder.class);
      }

      // Construct using network.message.ServerResponses.Login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        clientId_ = 0;

        playerNum_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return network.message.ServerResponses.internal_static_server_responses_Login_descriptor;
      }

      public network.message.ServerResponses.Login getDefaultInstanceForType() {
        return network.message.ServerResponses.Login.getDefaultInstance();
      }

      public network.message.ServerResponses.Login build() {
        network.message.ServerResponses.Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public network.message.ServerResponses.Login buildPartial() {
        network.message.ServerResponses.Login result = new network.message.ServerResponses.Login(this);
        result.clientId_ = clientId_;
        result.playerNum_ = playerNum_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof network.message.ServerResponses.Login) {
          return mergeFrom((network.message.ServerResponses.Login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(network.message.ServerResponses.Login other) {
        if (other == network.message.ServerResponses.Login.getDefaultInstance()) return this;
        if (other.getClientId() != 0) {
          setClientId(other.getClientId());
        }
        if (other.getPlayerNum() != 0) {
          setPlayerNum(other.getPlayerNum());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        network.message.ServerResponses.Login parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (network.message.ServerResponses.Login) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int clientId_ ;
      /**
       * <code>optional int32 clientId = 1;</code>
       */
      public int getClientId() {
        return clientId_;
      }
      /**
       * <code>optional int32 clientId = 1;</code>
       */
      public Builder setClientId(int value) {
        
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 clientId = 1;</code>
       */
      public Builder clearClientId() {
        
        clientId_ = 0;
        onChanged();
        return this;
      }

      private int playerNum_ ;
      /**
       * <code>optional int32 playerNum = 2;</code>
       */
      public int getPlayerNum() {
        return playerNum_;
      }
      /**
       * <code>optional int32 playerNum = 2;</code>
       */
      public Builder setPlayerNum(int value) {
        
        playerNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 playerNum = 2;</code>
       */
      public Builder clearPlayerNum() {
        
        playerNum_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:server.responses.Login)
    }

    // @@protoc_insertion_point(class_scope:server.responses.Login)
    private static final network.message.ServerResponses.Login DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new network.message.ServerResponses.Login();
    }

    public static network.message.ServerResponses.Login getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Login>
        PARSER = new com.google.protobuf.AbstractParser<Login>() {
      public Login parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Login(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Login> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Login> getParserForType() {
      return PARSER;
    }

    public network.message.ServerResponses.Login getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:server.responses.Command)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool accepted = 1;</code>
     */
    boolean getAccepted();
  }
  /**
   * Protobuf type {@code server.responses.Command}
   */
  public  static final class Command extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:server.responses.Command)
      CommandOrBuilder {
    // Use Command.newBuilder() to construct.
    private Command(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Command() {
      accepted_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Command(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              accepted_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.message.ServerResponses.internal_static_server_responses_Command_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.message.ServerResponses.internal_static_server_responses_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.message.ServerResponses.Command.class, network.message.ServerResponses.Command.Builder.class);
    }

    public static final int ACCEPTED_FIELD_NUMBER = 1;
    private boolean accepted_;
    /**
     * <code>optional bool accepted = 1;</code>
     */
    public boolean getAccepted() {
      return accepted_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (accepted_ != false) {
        output.writeBool(1, accepted_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (accepted_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, accepted_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static network.message.ServerResponses.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.ServerResponses.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.ServerResponses.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.ServerResponses.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.ServerResponses.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.ServerResponses.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static network.message.ServerResponses.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static network.message.ServerResponses.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static network.message.ServerResponses.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.ServerResponses.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(network.message.ServerResponses.Command prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code server.responses.Command}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:server.responses.Command)
        network.message.ServerResponses.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return network.message.ServerResponses.internal_static_server_responses_Command_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return network.message.ServerResponses.internal_static_server_responses_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                network.message.ServerResponses.Command.class, network.message.ServerResponses.Command.Builder.class);
      }

      // Construct using network.message.ServerResponses.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        accepted_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return network.message.ServerResponses.internal_static_server_responses_Command_descriptor;
      }

      public network.message.ServerResponses.Command getDefaultInstanceForType() {
        return network.message.ServerResponses.Command.getDefaultInstance();
      }

      public network.message.ServerResponses.Command build() {
        network.message.ServerResponses.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public network.message.ServerResponses.Command buildPartial() {
        network.message.ServerResponses.Command result = new network.message.ServerResponses.Command(this);
        result.accepted_ = accepted_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof network.message.ServerResponses.Command) {
          return mergeFrom((network.message.ServerResponses.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(network.message.ServerResponses.Command other) {
        if (other == network.message.ServerResponses.Command.getDefaultInstance()) return this;
        if (other.getAccepted() != false) {
          setAccepted(other.getAccepted());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        network.message.ServerResponses.Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (network.message.ServerResponses.Command) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean accepted_ ;
      /**
       * <code>optional bool accepted = 1;</code>
       */
      public boolean getAccepted() {
        return accepted_;
      }
      /**
       * <code>optional bool accepted = 1;</code>
       */
      public Builder setAccepted(boolean value) {
        
        accepted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool accepted = 1;</code>
       */
      public Builder clearAccepted() {
        
        accepted_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:server.responses.Command)
    }

    // @@protoc_insertion_point(class_scope:server.responses.Command)
    private static final network.message.ServerResponses.Command DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new network.message.ServerResponses.Command();
    }

    public static network.message.ServerResponses.Command getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Command>
        PARSER = new com.google.protobuf.AbstractParser<Command>() {
      public Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Command(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Command> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Command> getParserForType() {
      return PARSER;
    }

    public network.message.ServerResponses.Command getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_server_responses_BaseResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_server_responses_BaseResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_server_responses_Login_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_server_responses_Login_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_server_responses_Command_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_server_responses_Command_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4src/main/proto/network/message/ServerR" +
      "esponses.proto\022\020server.responses\"\227\001\n\014Bas" +
      "eResponse\022\020\n\010clientId\030\001 \001(\005\022\021\n\tmessageId" +
      "\030\002 \001(\005\022(\n\005login\030\003 \001(\0132\027.server.responses" +
      ".LoginH\000\022,\n\007command\030\004 \001(\0132\031.server.respo" +
      "nses.CommandH\000B\n\n\010response\",\n\005Login\022\020\n\010c" +
      "lientId\030\001 \001(\005\022\021\n\tplayerNum\030\002 \001(\005\"\033\n\007Comm" +
      "and\022\020\n\010accepted\030\001 \001(\010B\"\n\017network.message" +
      "B\017ServerResponsesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_server_responses_BaseResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_server_responses_BaseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_server_responses_BaseResponse_descriptor,
        new java.lang.String[] { "ClientId", "MessageId", "Login", "Command", "Response", });
    internal_static_server_responses_Login_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_server_responses_Login_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_server_responses_Login_descriptor,
        new java.lang.String[] { "ClientId", "PlayerNum", });
    internal_static_server_responses_Command_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_server_responses_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_server_responses_Command_descriptor,
        new java.lang.String[] { "Accepted", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
