// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/network/message/ServerCommands.proto

package network.message;

public final class ServerCommands {
  private ServerCommands() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BaseCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:server.commands.BaseCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .server.commands.BaseCommand.Type type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .server.commands.BaseCommand.Type type = 1;</code>
     */
    network.message.ServerCommands.BaseCommand.Type getType();

    /**
     * <code>optional int32 messageId = 2;</code>
     */
    int getMessageId();

    /**
     * <code>optional .server.commands.UpdateBoardState updateBoardState = 4;</code>
     */
    network.message.ServerCommands.UpdateBoardState getUpdateBoardState();
    /**
     * <code>optional .server.commands.UpdateBoardState updateBoardState = 4;</code>
     */
    network.message.ServerCommands.UpdateBoardStateOrBuilder getUpdateBoardStateOrBuilder();

    public network.message.ServerCommands.BaseCommand.CommandCase getCommandCase();
  }
  /**
   * Protobuf type {@code server.commands.BaseCommand}
   */
  public  static final class BaseCommand extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:server.commands.BaseCommand)
      BaseCommandOrBuilder {
    // Use BaseCommand.newBuilder() to construct.
    private BaseCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BaseCommand() {
      type_ = 0;
      messageId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BaseCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 16: {

              messageId_ = input.readInt32();
              break;
            }
            case 34: {
              network.message.ServerCommands.UpdateBoardState.Builder subBuilder = null;
              if (commandCase_ == 4) {
                subBuilder = ((network.message.ServerCommands.UpdateBoardState) command_).toBuilder();
              }
              command_ =
                  input.readMessage(network.message.ServerCommands.UpdateBoardState.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((network.message.ServerCommands.UpdateBoardState) command_);
                command_ = subBuilder.buildPartial();
              }
              commandCase_ = 4;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.message.ServerCommands.internal_static_server_commands_BaseCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.message.ServerCommands.internal_static_server_commands_BaseCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.message.ServerCommands.BaseCommand.class, network.message.ServerCommands.BaseCommand.Builder.class);
    }

    /**
     * Protobuf enum {@code server.commands.BaseCommand.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UPDATE_BOARD_STATE = 0;</code>
       */
      UPDATE_BOARD_STATE(0, 0),
      UNRECOGNIZED(-1, -1),
      ;

      /**
       * <code>UPDATE_BOARD_STATE = 0;</code>
       */
      public static final int UPDATE_BOARD_STATE_VALUE = 0;


      public final int getNumber() {
        if (index == -1) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return UPDATE_BOARD_STATE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return network.message.ServerCommands.BaseCommand.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:server.commands.BaseCommand.Type)
    }

    private int commandCase_ = 0;
    private java.lang.Object command_;
    public enum CommandCase
        implements com.google.protobuf.Internal.EnumLite {
      UPDATEBOARDSTATE(4),
      COMMAND_NOT_SET(0);
      private int value = 0;
      private CommandCase(int value) {
        this.value = value;
      }
      public static CommandCase valueOf(int value) {
        switch (value) {
          case 4: return UPDATEBOARDSTATE;
          case 0: return COMMAND_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public CommandCase
    getCommandCase() {
      return CommandCase.valueOf(
          commandCase_);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .server.commands.BaseCommand.Type type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .server.commands.BaseCommand.Type type = 1;</code>
     */
    public network.message.ServerCommands.BaseCommand.Type getType() {
      network.message.ServerCommands.BaseCommand.Type result = network.message.ServerCommands.BaseCommand.Type.valueOf(type_);
      return result == null ? network.message.ServerCommands.BaseCommand.Type.UNRECOGNIZED : result;
    }

    public static final int MESSAGEID_FIELD_NUMBER = 2;
    private int messageId_;
    /**
     * <code>optional int32 messageId = 2;</code>
     */
    public int getMessageId() {
      return messageId_;
    }

    public static final int UPDATEBOARDSTATE_FIELD_NUMBER = 4;
    /**
     * <code>optional .server.commands.UpdateBoardState updateBoardState = 4;</code>
     */
    public network.message.ServerCommands.UpdateBoardState getUpdateBoardState() {
      if (commandCase_ == 4) {
         return (network.message.ServerCommands.UpdateBoardState) command_;
      }
      return network.message.ServerCommands.UpdateBoardState.getDefaultInstance();
    }
    /**
     * <code>optional .server.commands.UpdateBoardState updateBoardState = 4;</code>
     */
    public network.message.ServerCommands.UpdateBoardStateOrBuilder getUpdateBoardStateOrBuilder() {
      if (commandCase_ == 4) {
         return (network.message.ServerCommands.UpdateBoardState) command_;
      }
      return network.message.ServerCommands.UpdateBoardState.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != network.message.ServerCommands.BaseCommand.Type.UPDATE_BOARD_STATE.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (messageId_ != 0) {
        output.writeInt32(2, messageId_);
      }
      if (commandCase_ == 4) {
        output.writeMessage(4, (network.message.ServerCommands.UpdateBoardState) command_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != network.message.ServerCommands.BaseCommand.Type.UPDATE_BOARD_STATE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (messageId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, messageId_);
      }
      if (commandCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (network.message.ServerCommands.UpdateBoardState) command_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static network.message.ServerCommands.BaseCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.ServerCommands.BaseCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.ServerCommands.BaseCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.ServerCommands.BaseCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.ServerCommands.BaseCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.ServerCommands.BaseCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static network.message.ServerCommands.BaseCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static network.message.ServerCommands.BaseCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static network.message.ServerCommands.BaseCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.ServerCommands.BaseCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(network.message.ServerCommands.BaseCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code server.commands.BaseCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:server.commands.BaseCommand)
        network.message.ServerCommands.BaseCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return network.message.ServerCommands.internal_static_server_commands_BaseCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return network.message.ServerCommands.internal_static_server_commands_BaseCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                network.message.ServerCommands.BaseCommand.class, network.message.ServerCommands.BaseCommand.Builder.class);
      }

      // Construct using network.message.ServerCommands.BaseCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        messageId_ = 0;

        commandCase_ = 0;
        command_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return network.message.ServerCommands.internal_static_server_commands_BaseCommand_descriptor;
      }

      public network.message.ServerCommands.BaseCommand getDefaultInstanceForType() {
        return network.message.ServerCommands.BaseCommand.getDefaultInstance();
      }

      public network.message.ServerCommands.BaseCommand build() {
        network.message.ServerCommands.BaseCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public network.message.ServerCommands.BaseCommand buildPartial() {
        network.message.ServerCommands.BaseCommand result = new network.message.ServerCommands.BaseCommand(this);
        result.type_ = type_;
        result.messageId_ = messageId_;
        if (commandCase_ == 4) {
          if (updateBoardStateBuilder_ == null) {
            result.command_ = command_;
          } else {
            result.command_ = updateBoardStateBuilder_.build();
          }
        }
        result.commandCase_ = commandCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof network.message.ServerCommands.BaseCommand) {
          return mergeFrom((network.message.ServerCommands.BaseCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(network.message.ServerCommands.BaseCommand other) {
        if (other == network.message.ServerCommands.BaseCommand.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getMessageId() != 0) {
          setMessageId(other.getMessageId());
        }
        switch (other.getCommandCase()) {
          case UPDATEBOARDSTATE: {
            mergeUpdateBoardState(other.getUpdateBoardState());
            break;
          }
          case COMMAND_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        network.message.ServerCommands.BaseCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (network.message.ServerCommands.BaseCommand) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int commandCase_ = 0;
      private java.lang.Object command_;
      public CommandCase
          getCommandCase() {
        return CommandCase.valueOf(
            commandCase_);
      }

      public Builder clearCommand() {
        commandCase_ = 0;
        command_ = null;
        onChanged();
        return this;
      }


      private int type_ = 0;
      /**
       * <code>optional .server.commands.BaseCommand.Type type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .server.commands.BaseCommand.Type type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .server.commands.BaseCommand.Type type = 1;</code>
       */
      public network.message.ServerCommands.BaseCommand.Type getType() {
        network.message.ServerCommands.BaseCommand.Type result = network.message.ServerCommands.BaseCommand.Type.valueOf(type_);
        return result == null ? network.message.ServerCommands.BaseCommand.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .server.commands.BaseCommand.Type type = 1;</code>
       */
      public Builder setType(network.message.ServerCommands.BaseCommand.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .server.commands.BaseCommand.Type type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int messageId_ ;
      /**
       * <code>optional int32 messageId = 2;</code>
       */
      public int getMessageId() {
        return messageId_;
      }
      /**
       * <code>optional int32 messageId = 2;</code>
       */
      public Builder setMessageId(int value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 messageId = 2;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilder<
          network.message.ServerCommands.UpdateBoardState, network.message.ServerCommands.UpdateBoardState.Builder, network.message.ServerCommands.UpdateBoardStateOrBuilder> updateBoardStateBuilder_;
      /**
       * <code>optional .server.commands.UpdateBoardState updateBoardState = 4;</code>
       */
      public network.message.ServerCommands.UpdateBoardState getUpdateBoardState() {
        if (updateBoardStateBuilder_ == null) {
          if (commandCase_ == 4) {
            return (network.message.ServerCommands.UpdateBoardState) command_;
          }
          return network.message.ServerCommands.UpdateBoardState.getDefaultInstance();
        } else {
          if (commandCase_ == 4) {
            return updateBoardStateBuilder_.getMessage();
          }
          return network.message.ServerCommands.UpdateBoardState.getDefaultInstance();
        }
      }
      /**
       * <code>optional .server.commands.UpdateBoardState updateBoardState = 4;</code>
       */
      public Builder setUpdateBoardState(network.message.ServerCommands.UpdateBoardState value) {
        if (updateBoardStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          command_ = value;
          onChanged();
        } else {
          updateBoardStateBuilder_.setMessage(value);
        }
        commandCase_ = 4;
        return this;
      }
      /**
       * <code>optional .server.commands.UpdateBoardState updateBoardState = 4;</code>
       */
      public Builder setUpdateBoardState(
          network.message.ServerCommands.UpdateBoardState.Builder builderForValue) {
        if (updateBoardStateBuilder_ == null) {
          command_ = builderForValue.build();
          onChanged();
        } else {
          updateBoardStateBuilder_.setMessage(builderForValue.build());
        }
        commandCase_ = 4;
        return this;
      }
      /**
       * <code>optional .server.commands.UpdateBoardState updateBoardState = 4;</code>
       */
      public Builder mergeUpdateBoardState(network.message.ServerCommands.UpdateBoardState value) {
        if (updateBoardStateBuilder_ == null) {
          if (commandCase_ == 4 &&
              command_ != network.message.ServerCommands.UpdateBoardState.getDefaultInstance()) {
            command_ = network.message.ServerCommands.UpdateBoardState.newBuilder((network.message.ServerCommands.UpdateBoardState) command_)
                .mergeFrom(value).buildPartial();
          } else {
            command_ = value;
          }
          onChanged();
        } else {
          if (commandCase_ == 4) {
            updateBoardStateBuilder_.mergeFrom(value);
          }
          updateBoardStateBuilder_.setMessage(value);
        }
        commandCase_ = 4;
        return this;
      }
      /**
       * <code>optional .server.commands.UpdateBoardState updateBoardState = 4;</code>
       */
      public Builder clearUpdateBoardState() {
        if (updateBoardStateBuilder_ == null) {
          if (commandCase_ == 4) {
            commandCase_ = 0;
            command_ = null;
            onChanged();
          }
        } else {
          if (commandCase_ == 4) {
            commandCase_ = 0;
            command_ = null;
          }
          updateBoardStateBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .server.commands.UpdateBoardState updateBoardState = 4;</code>
       */
      public network.message.ServerCommands.UpdateBoardState.Builder getUpdateBoardStateBuilder() {
        return getUpdateBoardStateFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .server.commands.UpdateBoardState updateBoardState = 4;</code>
       */
      public network.message.ServerCommands.UpdateBoardStateOrBuilder getUpdateBoardStateOrBuilder() {
        if ((commandCase_ == 4) && (updateBoardStateBuilder_ != null)) {
          return updateBoardStateBuilder_.getMessageOrBuilder();
        } else {
          if (commandCase_ == 4) {
            return (network.message.ServerCommands.UpdateBoardState) command_;
          }
          return network.message.ServerCommands.UpdateBoardState.getDefaultInstance();
        }
      }
      /**
       * <code>optional .server.commands.UpdateBoardState updateBoardState = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          network.message.ServerCommands.UpdateBoardState, network.message.ServerCommands.UpdateBoardState.Builder, network.message.ServerCommands.UpdateBoardStateOrBuilder> 
          getUpdateBoardStateFieldBuilder() {
        if (updateBoardStateBuilder_ == null) {
          if (!(commandCase_ == 4)) {
            command_ = network.message.ServerCommands.UpdateBoardState.getDefaultInstance();
          }
          updateBoardStateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              network.message.ServerCommands.UpdateBoardState, network.message.ServerCommands.UpdateBoardState.Builder, network.message.ServerCommands.UpdateBoardStateOrBuilder>(
                  (network.message.ServerCommands.UpdateBoardState) command_,
                  getParentForChildren(),
                  isClean());
          command_ = null;
        }
        commandCase_ = 4;
        onChanged();;
        return updateBoardStateBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:server.commands.BaseCommand)
    }

    // @@protoc_insertion_point(class_scope:server.commands.BaseCommand)
    private static final network.message.ServerCommands.BaseCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new network.message.ServerCommands.BaseCommand();
    }

    public static network.message.ServerCommands.BaseCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseCommand>
        PARSER = new com.google.protobuf.AbstractParser<BaseCommand>() {
      public BaseCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new BaseCommand(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<BaseCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseCommand> getParserForType() {
      return PARSER;
    }

    public network.message.ServerCommands.BaseCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UpdateBoardStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:server.commands.UpdateBoardState)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code server.commands.UpdateBoardState}
   *
   * <pre>
   * stuff here
   * </pre>
   */
  public  static final class UpdateBoardState extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:server.commands.UpdateBoardState)
      UpdateBoardStateOrBuilder {
    // Use UpdateBoardState.newBuilder() to construct.
    private UpdateBoardState(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UpdateBoardState() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UpdateBoardState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.message.ServerCommands.internal_static_server_commands_UpdateBoardState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.message.ServerCommands.internal_static_server_commands_UpdateBoardState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.message.ServerCommands.UpdateBoardState.class, network.message.ServerCommands.UpdateBoardState.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static network.message.ServerCommands.UpdateBoardState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.ServerCommands.UpdateBoardState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.ServerCommands.UpdateBoardState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.ServerCommands.UpdateBoardState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.ServerCommands.UpdateBoardState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.ServerCommands.UpdateBoardState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static network.message.ServerCommands.UpdateBoardState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static network.message.ServerCommands.UpdateBoardState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static network.message.ServerCommands.UpdateBoardState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.ServerCommands.UpdateBoardState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(network.message.ServerCommands.UpdateBoardState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code server.commands.UpdateBoardState}
     *
     * <pre>
     * stuff here
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:server.commands.UpdateBoardState)
        network.message.ServerCommands.UpdateBoardStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return network.message.ServerCommands.internal_static_server_commands_UpdateBoardState_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return network.message.ServerCommands.internal_static_server_commands_UpdateBoardState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                network.message.ServerCommands.UpdateBoardState.class, network.message.ServerCommands.UpdateBoardState.Builder.class);
      }

      // Construct using network.message.ServerCommands.UpdateBoardState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return network.message.ServerCommands.internal_static_server_commands_UpdateBoardState_descriptor;
      }

      public network.message.ServerCommands.UpdateBoardState getDefaultInstanceForType() {
        return network.message.ServerCommands.UpdateBoardState.getDefaultInstance();
      }

      public network.message.ServerCommands.UpdateBoardState build() {
        network.message.ServerCommands.UpdateBoardState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public network.message.ServerCommands.UpdateBoardState buildPartial() {
        network.message.ServerCommands.UpdateBoardState result = new network.message.ServerCommands.UpdateBoardState(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof network.message.ServerCommands.UpdateBoardState) {
          return mergeFrom((network.message.ServerCommands.UpdateBoardState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(network.message.ServerCommands.UpdateBoardState other) {
        if (other == network.message.ServerCommands.UpdateBoardState.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        network.message.ServerCommands.UpdateBoardState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (network.message.ServerCommands.UpdateBoardState) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:server.commands.UpdateBoardState)
    }

    // @@protoc_insertion_point(class_scope:server.commands.UpdateBoardState)
    private static final network.message.ServerCommands.UpdateBoardState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new network.message.ServerCommands.UpdateBoardState();
    }

    public static network.message.ServerCommands.UpdateBoardState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateBoardState>
        PARSER = new com.google.protobuf.AbstractParser<UpdateBoardState>() {
      public UpdateBoardState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new UpdateBoardState(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<UpdateBoardState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateBoardState> getParserForType() {
      return PARSER;
    }

    public network.message.ServerCommands.UpdateBoardState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_server_commands_BaseCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_server_commands_BaseCommand_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_server_commands_UpdateBoardState_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_server_commands_UpdateBoardState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3src/main/proto/network/message/ServerC" +
      "ommands.proto\022\017server.commands\"\273\001\n\013BaseC" +
      "ommand\022/\n\004type\030\001 \001(\0162!.server.commands.B" +
      "aseCommand.Type\022\021\n\tmessageId\030\002 \001(\005\022=\n\020up" +
      "dateBoardState\030\004 \001(\0132!.server.commands.U" +
      "pdateBoardStateH\000\"\036\n\004Type\022\026\n\022UPDATE_BOAR" +
      "D_STATE\020\000B\t\n\007command\"\022\n\020UpdateBoardState" +
      "B!\n\017network.messageB\016ServerCommandsb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_server_commands_BaseCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_server_commands_BaseCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_server_commands_BaseCommand_descriptor,
        new java.lang.String[] { "Type", "MessageId", "UpdateBoardState", "Command", });
    internal_static_server_commands_UpdateBoardState_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_server_commands_UpdateBoardState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_server_commands_UpdateBoardState_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
