package rendering.obstacles;

/**
 * Created by Brian on 3/6/2016.
 */
public enum ObstacleType {
    ASTEROID_BASE_CORE_0,
    ASTEROID_BASE_CORE_1,
    ASTEROID_BASE_CORE_2,
    ASTEROID_BASE_CORE_3,
    ASTEROID_BASE_CORE_4,
    ASTEROID_BASE_CORE_5,
    ASTEROID_TFA_CORE_0,
    ASTEROID_TFA_CORE_1,
    ASTEROID_TFA_CORE_2,
    ASTEROID_TFA_CORE_3,
    ASTEROID_TFA_CORE_4,
    ASTEROID_TFA_CORE_5,
    DEBRIS_0,
    DEBRIS_1,
    DEBRIS_2,
    DEBRIS_3,
    DEBRIS_4,
    DEBRIS_5,
}
